import { useState } from "react";
import { Check, ChevronDown, Globe2, Search, ShieldCheck, X } from "lucide-react";
import { REGION_POLICIES, useUserRegion } from "@/contexts/UserRegionContext";

export default function RegionSwitcher() {
  const { policy, source, isKycVerified, setUserCountry } = useUserRegion();
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const regions = Object.values(REGION_POLICIES).filter(item => `${item.name} ${item.currency}`.toLowerCase().includes(query.toLowerCase()));
  const status = isKycVerified ? "KYC verified" : source === "ip_detected" ? "Detected region" : "Active region";

  return <>
    <button onClick={() => setOpen(true)} aria-label="Change region and fiat currency" style={{ display: "flex", alignItems: "center", gap: 7, minHeight: 34, padding: "6px 9px", borderRadius: 10, border: "1px solid rgba(255,255,255,.12)", background: "rgba(255,255,255,.04)", color: "#f5f5f5", fontSize: 11, fontWeight: 800 }}><span>{policy.flag}</span><span>{policy.currency}</span><ChevronDown size={13} color="#0ecb81" /></button>
    {open && <div onClick={() => setOpen(false)} style={{ position: "fixed", inset: 0, zIndex: 140, display: "flex", alignItems: "flex-end", background: "rgba(0,0,0,.76)", backdropFilter: "blur(7px)" }}><section onClick={e => e.stopPropagation()} style={{ width: "100%", maxWidth: 560, maxHeight: "84vh", overflowY: "auto", margin: "0 auto", padding: "20px 16px calc(28px + env(safe-area-inset-bottom))", borderRadius: "24px 24px 0 0", background: "#181a20", borderTop: "1px solid rgba(14,203,129,.45)" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 15 }}><div><strong style={{ fontSize: 16 }}>Region & Fiat</strong><p style={{ margin: "5px 0 0", color: "#929aa5", fontSize: 10 }}>{status}. KYC-approved country takes priority.</p></div><button onClick={() => setOpen(false)} style={{ border: 0, background: "none", color: "#929aa5" }}><X size={19} /></button></div>{isKycVerified && <div style={{ display: "flex", alignItems: "center", gap: 8, padding: 10, marginBottom: 12, borderRadius: 11, background: "rgba(14,203,129,.08)", border: "1px solid rgba(14,203,129,.2)", color: "#0ecb81", fontSize: 10, fontWeight: 700 }}><ShieldCheck size={15} /> Your verified KYC country controls compliance-sensitive routing.</div>}<div style={{ display: "flex", alignItems: "center", gap: 8, padding: "10px 12px", borderRadius: 11, border: "1px solid #2b313a", background: "#0b0e11", marginBottom: 14 }}><Search size={15} color="#929aa5" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search country or currency" style={{ flex: 1, border: 0, outline: 0, background: "transparent", color: "#f5f5f5", fontSize: 12 }} /></div><div style={{ display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: 8 }}>{regions.map(item => <button key={item.code} onClick={() => { setUserCountry(item.code); setOpen(false); setQuery(""); }} style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, padding: 11, borderRadius: 12, border: `1px solid ${item.code === policy.code ? "rgba(14,203,129,.55)" : "#2b313a"}`, background: item.code === policy.code ? "rgba(14,203,129,.1)" : "#0b0e11", color: "#f5f5f5", textAlign: "left" }}><span style={{ display: "flex", alignItems: "center", gap: 8 }}><span style={{ fontSize: 20 }}>{item.flag}</span><span><strong style={{ display: "block", fontSize: 11 }}>{item.name}</strong><small style={{ display: "block", marginTop: 3, color: "#0ecb81", fontSize: 9, fontWeight: 800 }}>{item.currency}</small></span></span>{item.code === policy.code && <Check size={15} color="#0ecb81" />}</button>)}</div><div style={{ display: "flex", alignItems: "center", gap: 7, marginTop: 15, color: "#929aa5", fontSize: 9 }}><Globe2 size={13} /> Changing the active view does not override a KYC restriction or create payment authorization.</div></section></div>}
  </>;
}
