import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, BarChart3, Check, ChevronRight, Copy, Download, ExternalLink, HelpCircle, History, Link2, MessageCircle, QrCode, Share2, ShieldCheck, Users, Wallet, X } from "lucide-react";
import { useLocation } from "wouter";
import { useState } from "react";
import { useToast } from "@/hooks/use-toast";

const BG = "#0b0e11", CARD = "#181a20", PANEL = "#1e2329", LINE = "#2b313a", FG = "#f5f5f5", DIM = "#929aa5", GOLD = "#f0b90b", GREEN = "#0ecb81";

type SheetKind = "rules" | "support" | "history" | "withdraw" | "qr" | null;

const TIERS = [
  { name: "Bronze Partner", rebate: "30% Fee Rebate", volume: "0 - $100k Monthly Volume", state: "Unlocked", color: DIM },
  { name: "Silver Partner", rebate: "40% Fee Rebate + 5% RWA Yield Share", volume: "$100k - $500k Monthly Volume", state: "ACTIVE TIER", color: GOLD },
  { name: "Gold VIP Executive Partner", rebate: "50% Fee Rebate + Custom VIP Support", volume: "> $500k Monthly Volume", state: "Locked", color: GREEN },
];

function Sheet({ kind, close, onWithdraw }: { kind: Exclude<SheetKind, null>; close: () => void; onWithdraw: () => void }) {
  const title = kind === "rules" ? "Commission Rules" : kind === "support" ? "Partner Support" : kind === "history" ? "Commission History" : kind === "withdraw" ? "Withdraw Commission" : "Referral QR Code";
  return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} style={{ position: "fixed", inset: 0, zIndex: 1000, display: "flex", alignItems: "flex-end", background: "rgba(0,0,0,.8)" }}>
    <div onClick={close} style={{ position: "absolute", inset: 0 }} />
    <motion.div initial={{ y: "100%" }} animate={{ y: 0 }} exit={{ y: "100%" }} style={{ position: "relative", width: "100%", maxHeight: "86dvh", overflowY: "auto", padding: "22px 16px calc(32px + env(safe-area-inset-bottom) + 72px)", background: BG, borderTop: `1px solid ${LINE}`, borderRadius: "24px 24px 0 0" }}>
      <div style={{ width: 40, height: 4, borderRadius: 99, background: LINE, margin: "0 auto 17px" }} />
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}><strong style={{ fontSize: 16 }}>{title}</strong><button onClick={close} style={{ border: 0, background: "none", color: DIM, padding: 8 }}><X size={20} /></button></div>
      {kind === "rules" && <div style={{ marginTop: 16 }}>{TIERS.map((tier, i) => <div key={tier.name} style={{ padding: "14px 0", borderBottom: i < 2 ? `1px solid ${LINE}` : "none" }}><div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}><div><strong style={{ display: "block", color: tier.color, fontSize: 13 }}>{tier.name}</strong><span style={{ display: "block", marginTop: 5, fontSize: 12, color: FG }}>{tier.rebate}</span><span style={{ display: "block", marginTop: 4, fontSize: 10, color: DIM }}>{tier.volume}</span></div><span style={{ height: 22, padding: "4px 8px", borderRadius: 6, color: tier.color, background: `${tier.color}18`, border: `1px solid ${tier.color}45`, fontSize: 9, fontWeight: 900, whiteSpace: "nowrap" }}>{tier.state}</span></div></div>)}</div>}
      {kind === "support" && <div style={{ marginTop: 16, color: DIM, fontSize: 12, lineHeight: 1.65 }}><div style={{ display: "flex", gap: 12, padding: 14, borderRadius: 14, background: CARD, border: `1px solid ${LINE}` }}><MessageCircle color={GOLD} size={20} /><div><strong style={{ display: "block", color: FG, fontSize: 13 }}>Partner Success Desk</strong><span>Get campaign planning, payout and tier support from our partner team.</span></div></div><button onClick={() => window.location.href = "/customer-service"} style={{ width: "100%", marginTop: 14, padding: 13, border: 0, borderRadius: 12, background: GOLD, color: BG, fontWeight: 900 }}>Open Partner Support</button></div>}
      {kind === "history" && <div style={{ marginTop: 16 }}>{[["Trading fee rebate", "+$1,240.00", "Aug 12, 2026"], ["RWA yield share", "+$380.00", "Aug 05, 2026"], ["Partner payout", "+$720.00", "Jul 29, 2026"]].map(([label, amount, date]) => <div key={label} style={{ display: "flex", alignItems: "center", gap: 10, padding: 13, marginBottom: 8, borderRadius: 13, background: CARD, border: `1px solid ${LINE}` }}><BarChart3 color={GREEN} size={18} /><div style={{ flex: 1 }}><strong style={{ display: "block", fontSize: 12 }}>{label}</strong><span style={{ color: DIM, fontSize: 10 }}>{date} · Credited</span></div><strong style={{ color: GREEN, fontSize: 12 }}>{amount}</strong></div>)}</div>}
      {kind === "withdraw" && <div style={{ marginTop: 16 }}><div style={{ padding: 15, borderRadius: 14, background: CARD, border: `1px solid ${LINE}` }}><span style={{ color: DIM, fontSize: 10 }}>AVAILABLE COMMISSION</span><strong style={{ display: "block", marginTop: 6, fontSize: 25 }}>Rs 850,000</strong><span style={{ color: GOLD, fontSize: 11 }}>≈ $3,035.00 USDT</span></div><div style={{ marginTop: 12, padding: 13, borderRadius: 12, background: PANEL, color: DIM, fontSize: 11, lineHeight: 1.55 }}>Payouts are processed to your verified wallet after compliance checks. Minimum withdrawal is 25 USDT.</div><button onClick={() => { onWithdraw(); close(); }} style={{ width: "100%", marginTop: 16, marginBottom: 8, padding: 14, border: 0, borderRadius: 12, background: GOLD, color: BG, fontWeight: 900 }}>Request Commission Payout</button></div>}
      {kind === "qr" && <div style={{ marginTop: 17, textAlign: "center" }}><div style={{ display: "grid", placeItems: "center", width: 190, height: 190, margin: "0 auto", borderRadius: 18, background: "repeating-linear-gradient(45deg,#fff 0 5px,#111 5px 10px)", border: `9px solid ${FG}` }}><QrCode size={82} color={BG} /></div><strong style={{ display: "block", marginTop: 16, fontSize: 13 }}>ORAKZAI_VIP</strong><span style={{ display: "block", color: DIM, fontSize: 10, marginTop: 5 }}>Scan to open your affiliate link</span></div>}
      {kind !== "withdraw" && <button onClick={close} style={{ width: "100%", marginTop: 18, marginBottom: 8, padding: 13, border: `1px solid ${LINE}`, borderRadius: 12, background: CARD, color: FG, fontWeight: 800 }}>Close</button>}
    </motion.div>
  </motion.div>;
}

export default function AffiliateProgram() {
  const [, nav] = useLocation();
  const { toast } = useToast();
  const [sheet, setSheet] = useState<SheetKind>(null);
  const [copied, setCopied] = useState(false);
  const copyLink = async () => { try { await navigator.clipboard.writeText("https://okzbyte.app/ref/ORAKZAI_VIP"); } catch {} setCopied(true); toast({ title: "Affiliate link copied", description: "Share it with your trading community." }); setTimeout(() => setCopied(false), 1800); };
  return <div style={{ minHeight: "100dvh", overflowX: "hidden", padding: "12px 16px calc(92px + env(safe-area-inset-bottom))", background: BG, color: FG, fontFamily: "-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif", WebkitFontSmoothing: "antialiased" }}>
    <header style={{ height: 48, display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 16 }}><div style={{ display: "flex", alignItems: "center", minWidth: 0 }}><button onClick={() => nav("/services")} style={{ border: 0, background: "none", color: DIM, padding: 8 }}><ArrowLeft size={20} /></button><strong style={{ fontSize: 16, letterSpacing: ".02em", whiteSpace: "nowrap" }}>Affiliate Portal</strong></div><div style={{ display: "flex", gap: 4 }}><button onClick={() => setSheet("rules")} aria-label="Commission rules" style={{ padding: 9, border: 0, background: "none", color: DIM }}><BarChart3 size={18} /></button><button onClick={() => setSheet("support")} aria-label="Partner support" style={{ padding: 9, border: 0, background: "none", color: DIM }}><HelpCircle size={19} /></button></div></header>
    <main style={{ maxWidth: 760, margin: "0 auto" }}>
      <section style={{ position: "relative", overflow: "hidden", padding: 20, marginBottom: 18, borderRadius: 18, border: `1px solid ${GOLD}55`, background: "linear-gradient(135deg,#181a20,#1e2329 56%,#0b0e11)", boxShadow: "0 18px 42px rgba(0,0,0,.2)" }}><span style={{ display: "inline-block", padding: "5px 9px", borderRadius: 6, border: `1px solid ${GOLD}45`, background: `${GOLD}16`, color: GOLD, fontSize: 10, fontWeight: 900 }}>VIP AFFILIATE TIER 1 • 40% REBATE</span><div style={{ marginTop: 12, color: DIM, fontSize: 10, letterSpacing: ".14em", fontWeight: 800 }}>TOTAL COMMISSIONS EARNED</div><div style={{ display: "flex", alignItems: "baseline", gap: 8, flexWrap: "wrap", marginTop: 3 }}><strong style={{ fontSize: 30, letterSpacing: "-.03em" }}>Rs 850,000</strong><span style={{ color: GOLD, fontSize: 12, fontWeight: 800 }}>($3,035.00 USDT)</span></div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginTop: 17, paddingTop: 13, borderTop: `1px solid ${LINE}` }}><div><span style={{ color: DIM, fontSize: 10 }}>INVITED TRADERS</span><strong style={{ display: "block", marginTop: 4, fontSize: 12 }}>142 Active Users</strong></div><div><span style={{ color: DIM, fontSize: 10 }}>TOTAL REFERRAL VOLUME</span><strong style={{ display: "block", marginTop: 4, color: GREEN, fontSize: 12 }}>$1.2M USDT Volume</strong></div></div><div style={{ display: "flex", gap: 8, marginTop: 17 }}><button onClick={() => setSheet("withdraw")} style={{ flex: 1, border: 0, borderRadius: 12, padding: 12, background: GOLD, color: BG, fontSize: 11, fontWeight: 900 }}>Withdraw Commission</button><button onClick={() => setSheet("history")} style={{ border: 0, borderRadius: 12, padding: "12px 14px", background: LINE, color: FG, fontSize: 11, fontWeight: 800 }}>View History</button></div></section>
      <section style={{ padding: 16, marginBottom: 18, borderRadius: 17, background: CARD, border: `1px solid ${LINE}`, boxShadow: "0 10px 28px rgba(0,0,0,.14)" }}><div style={{ marginBottom: 12, color: DIM, fontSize: 10, fontWeight: 900, letterSpacing: ".12em" }}>YOUR UNIQUE AFFILIATE LINK</div><div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 11 }}><div style={{ flex: 1, minWidth: 0, overflow: "hidden", border: `1px solid ${LINE}`, borderRadius: 11, padding: "11px 10px", background: BG, color: GOLD, fontSize: 10, fontFamily: "monospace", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>https://okzbyte.app/ref/ORAKZAI_VIP</div><button onClick={copyLink} style={{ flexShrink: 0, border: 0, borderRadius: 11, padding: "11px 13px", background: GOLD, color: BG, fontSize: 10, fontWeight: 900 }}>{copied ? <Check size={14} /> : "Copy"}</button></div><div style={{ display: "flex", alignItems: "center", gap: 8 }}><div style={{ flex: 1, minWidth: 0, padding: "10px 11px", overflow: "hidden", border: `1px solid ${LINE}`, borderRadius: 9, background: PANEL, color: FG, fontSize: 11, fontWeight: 800, fontFamily: "monospace", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>Referral Code: ORAKZAI_VIP</div><button onClick={() => setSheet("qr")} style={{ display: "flex", alignItems: "center", gap: 5, border: `1px solid ${GOLD}40`, borderRadius: 9, padding: "10px 11px", background: LINE, color: GOLD, fontSize: 10, fontWeight: 800 }}><QrCode size={14} /> QR</button></div></section>
      <div style={{ margin: "0 4px 10px", color: DIM, fontSize: 10, fontWeight: 900, letterSpacing: ".12em" }}>PARTNER REBATE TIERS</div><section style={{ padding: "4px 14px", marginBottom: 18, borderRadius: 17, background: CARD, border: `1px solid ${LINE}` }}>{TIERS.map((tier, i) => <div key={tier.name} style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, padding: "14px 0", borderBottom: i < TIERS.length - 1 ? `1px solid ${LINE}` : "none" }}><div style={{ minWidth: 0 }}><strong style={{ display: "block", color: tier.color, fontSize: 12 }}>{tier.rebate}</strong><span style={{ display: "block", marginTop: 4, color: DIM, fontSize: 10 }}>{tier.name} · {tier.volume}</span></div><span style={{ flexShrink: 0, padding: "5px 7px", borderRadius: 6, color: tier.color, background: `${tier.color}18`, border: `1px solid ${tier.color}40`, fontSize: 9, fontWeight: 900 }}>{tier.state}</span></div>)}</section>
      <div style={{ margin: "0 4px 10px", color: DIM, fontSize: 10, fontWeight: 900, letterSpacing: ".12em" }}>AFFILIATE TOOLKIT</div><section style={{ display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: 10 }}><button onClick={() => toast({ title: "Brand Media Kit", description: "Official OkzByte logo and banner assets are being prepared." })} style={{ minHeight: 104, padding: 13, textAlign: "left", border: `1px solid ${LINE}`, borderRadius: 14, background: CARD, color: FG }}><Download color={GOLD} size={20} /><strong style={{ display: "block", marginTop: 9, fontSize: 11 }}>Brand Media Kit</strong><span style={{ display: "block", marginTop: 4, color: DIM, fontSize: 10, lineHeight: 1.35 }}>Official OkzByte logos & ad assets</span></button><button onClick={() => toast({ title: "Sub-Affiliate Links", description: "Campaign tracking link tools are available through Partner Support." })} style={{ minHeight: 104, padding: 13, textAlign: "left", border: `1px solid ${LINE}`, borderRadius: 14, background: CARD, color: FG }}><Link2 color={GREEN} size={20} /><strong style={{ display: "block", marginTop: 9, fontSize: 11 }}>Sub-Affiliate Links</strong><span style={{ display: "block", marginTop: 4, color: DIM, fontSize: 10, lineHeight: 1.35 }}>Track YouTube, Telegram & social campaigns</span></button></section>
      <section style={{ display: "flex", gap: 9, alignItems: "flex-start", marginTop: 16, padding: 13, borderRadius: 13, border: `1px solid ${LINE}`, color: DIM, fontSize: 10, lineHeight: 1.5 }}><ShieldCheck size={16} color={GOLD} />Commission rebates and yield shares are subject to partner eligibility, compliance review and the applicable campaign terms.</section>
    </main>
    <nav style={{ position: "fixed", inset: "auto 0 0", zIndex: 50, height: "calc(64px + env(safe-area-inset-bottom))", paddingBottom: "env(safe-area-inset-bottom)", display: "flex", justifyContent: "space-around", alignItems: "center", background: "rgba(11,14,17,.95)", borderTop: `1px solid ${LINE}`, backdropFilter: "blur(15px)" }}>{[["Home","/"],["Markets","/markets"],["Trade","/trade"],["Assets","/wallet"],["Profile","/profile"]].map(([label, href]) => <button key={label} onClick={() => nav(href)} style={{ border: 0, background: "none", color: label === "Assets" ? GOLD : DIM, fontSize: 10, fontWeight: 700 }}>{label}</button>)}</nav>
    <AnimatePresence>{sheet && <Sheet kind={sheet} close={() => setSheet(null)} onWithdraw={() => toast({ title: "Payout request submitted", description: "Your commission withdrawal is queued for compliance review." })} />}</AnimatePresence>
  </div>;
}
