import { useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { useLocation } from "wouter";
import {
  ArrowLeft, ChevronDown, ClipboardList, Clock3, ExternalLink,
  Filter, History, Rocket, ShieldCheck, User, Wallet, X, Zap,
} from "lucide-react";
import type { LaunchpadProject, ProjectStatus } from "@/types/launchpad";

const BG = "#0B0E11";
const CARD = "#12161C";
const PANEL = "#1E2329";
const LINE = "#1E2329";
const GREEN = "#0ECB81";
const RED = "#F6465D";
const GOLD = "#F0B90B";
const DIM = "#848E9C";
const FG = "#EAECEF";

type Product = "Token Sale" | "Launchpool" | "HODLer Airdrop";
type FilterTab = "All" | "Upcoming" | "Active" | "Completed";
type Project = Omit<LaunchpadProject, "type"> & { type: "LAUNCHPAD" | "LAUNCHPOOL" | "AIRDROP" | "LOTTERY"; product: Product; progress: number; accent: string; shortName: string };

const PROJECTS: Project[] = [
  { id: "xter", name: "XTER", shortName: "X", symbol: "XTER", logoUrl: "/logo-ob-shield.png", network: "OKZ Chain", type: "LAUNCHPAD", status: "ACTIVE", description: "Infrastructure for a more open, composable internet.", website: "#", whitepaper: "#", socials: {}, tokenPriceUSD: 0.024, totalAllocation: 18750000, hardCapUSD: 450000, subscriptionStart: "2026-08-01T00:00:00Z", subscriptionEnd: "2026-08-28T00:00:00Z", distributionDate: "2026-08-30T00:00:00Z", minAllocationToken: 100, maxAllocationToken: 25000, totalCommittedTokens: 76, participantCount: 42816, product: "Token Sale", progress: 76, accent: GOLD },
  { id: "genius", name: "GENIUS", shortName: "G", symbol: "GENIUS", logoUrl: "/logo-ob-shield.png", network: "Ethereum", type: "LAUNCHPOOL", status: "UPCOMING", description: "A community-owned intelligence protocol for Web3.", website: "#", whitepaper: "#", socials: {}, tokenPriceUSD: 0.18, totalAllocation: 4200000, hardCapUSD: 756000, subscriptionStart: "2026-09-01T00:00:00Z", subscriptionEnd: "2026-09-04T00:00:00Z", distributionDate: "2026-09-06T00:00:00Z", minAllocationToken: 0, maxAllocationToken: 0, totalCommittedTokens: 0, participantCount: 0, product: "Launchpool", progress: 0, accent: "#6F8CFF" },
  { id: "aigensyn", name: "AIGENSYN", shortName: "A", symbol: "AIGENSYN", logoUrl: "/logo-ob-shield.png", network: "Arbitrum", type: "AIRDROP", status: "UPCOMING", description: "Agentic coordination for the next generation of protocols.", website: "#", whitepaper: "#", socials: {}, tokenPriceUSD: 0, totalAllocation: 9600000, hardCapUSD: 0, subscriptionStart: "2026-09-10T00:00:00Z", subscriptionEnd: "2026-09-12T00:00:00Z", distributionDate: "2026-09-14T00:00:00Z", minAllocationToken: 0, maxAllocationToken: 0, totalCommittedTokens: 0, participantCount: 0, product: "HODLer Airdrop", progress: 0, accent: GREEN },
  { id: "opg", name: "OPG", shortName: "O", symbol: "OPG", logoUrl: "/logo-ob-shield.png", network: "OKZ Chain", type: "LAUNCHPAD", status: "COMPLETED", description: "A high-throughput settlement layer for real-world value.", website: "#", whitepaper: "#", socials: {}, tokenPriceUSD: 0.042, totalAllocation: 12000000, hardCapUSD: 504000, subscriptionStart: "2026-07-01T00:00:00Z", subscriptionEnd: "2026-07-18T00:00:00Z", distributionDate: "2026-07-20T00:00:00Z", minAllocationToken: 0, maxAllocationToken: 0, totalCommittedTokens: 100, participantCount: 18492, product: "Token Sale", progress: 100, accent: "#A97BFF" },
];

const STATUS: Record<ProjectStatus, string> = { UPCOMING: "Upcoming", ACTIVE: "Live now", CALCULATING: "Calculating", COMPLETED: "Completed" };
const TABS = ["Launchpad", "Launchpool", "Airdrops", "History"];
const NAV = [
  { label: "Launchpad", Icon: Rocket, href: "/launchpad" },
  { label: "Orders", Icon: ClipboardList, href: "/trades" },
  { label: "Wallet", Icon: Wallet, href: "/wallet" },
  { label: "Profile", Icon: User, href: "/profile" },
];
const money = (v: number) => v === 0 ? "Snapshot" : `$${v.toFixed(v < 1 ? 3 : 2)}`;
const compact = (v: number) => v >= 1_000_000 ? `${(v / 1_000_000).toFixed(2)}M` : v >= 1_000 ? `${(v / 1_000).toFixed(2)}K` : v.toLocaleString();

function StatusPill({ status }: { status: ProjectStatus }) {
  const tone = status === "ACTIVE" ? { color: GREEN, bg: `${GREEN}18` } : status === "UPCOMING" ? { color: GOLD, bg: `${GOLD}18` } : { color: DIM, bg: `${PANEL}88` };
  return <span style={{ color: tone.color, background: tone.bg, border: `1px solid ${tone.color}44`, borderRadius: 5, padding: "3px 7px", fontSize: 10, fontWeight: 700, whiteSpace: "nowrap" }}>{STATUS[status]}</span>;
}

function ProjectAvatar({ project }: { project: Project }) {
  return <div style={{ width: 38, height: 38, borderRadius: "50%", display: "grid", placeItems: "center", flexShrink: 0, background: `${project.accent}20`, color: project.accent, border: `1px solid ${project.accent}66`, fontWeight: 800 }}>{project.shortName}</div>;
}

function ProjectCard({ project, onSelect }: { project: Project; onSelect: (p: Project) => void }) {
  const active = project.status === "ACTIVE";
  return <motion.div initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .18 }} style={{ margin: "0 12px 10px", padding: "14px 14px 12px", background: CARD, border: "1px solid #2B313A", borderRadius: 14 }}>
    <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 10, marginBottom: 13 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 10, minWidth: 0 }}><ProjectAvatar project={project} /><div style={{ minWidth: 0 }}><div style={{ display: "flex", alignItems: "center", gap: 7, flexWrap: "wrap" }}><span style={{ color: FG, fontSize: 14, fontWeight: 700 }}>{project.name}</span><StatusPill status={project.status} /></div><div style={{ color: DIM, fontSize: 11, marginTop: 3, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{project.symbol} · {project.network} · {project.product}</div></div></div>
      <span style={{ color: DIM, fontSize: 11, whiteSpace: "nowrap" }}>{project.participantCount ? `${compact(project.participantCount)} users` : "Not started"}</span>
    </div>
    <div style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", gap: 12 }}><div style={{ flex: 1, minWidth: 0 }}><div style={{ display: "flex", alignItems: "baseline", gap: 4, marginBottom: 9 }}><span style={{ color: DIM, fontSize: 12 }}>Price</span><span style={{ color: active ? GREEN : FG, fontSize: 25, lineHeight: 1, fontWeight: 800 }}>{money(project.tokenPriceUSD)}</span></div><div style={{ color: DIM, fontSize: 12, lineHeight: 1.6 }}>Allocation <span style={{ color: FG }}>{compact(project.totalAllocation)} {project.symbol}</span></div><div style={{ color: DIM, fontSize: 12, lineHeight: 1.6 }}>Pool cap <span style={{ color: FG }}>{project.hardCapUSD ? `$${compact(project.hardCapUSD)}` : "Community"}</span></div></div><button onClick={() => onSelect(project)} style={{ padding: "10px 18px", borderRadius: 22, background: active ? GOLD : PANEL, color: active ? BG : FG, fontWeight: 700, fontSize: 14, border: active ? "none" : `1px solid #39424D`, cursor: "pointer", flexShrink: 0 }}>{active ? "Subscribe" : project.status === "UPCOMING" ? "View" : "Archive"}</button></div>
    <div style={{ display: "flex", alignItems: "center", gap: 7, marginTop: 12, paddingTop: 10, borderTop: "1px solid rgba(255,255,255,.05)" }}><Clock3 size={13} color={DIM} /><span style={{ color: DIM, fontSize: 11 }}>{active ? "Subscription closes 28 Aug 2026" : project.status === "UPCOMING" ? "Opens soon" : "Distribution completed"}</span><span style={{ marginLeft: "auto", color: project.accent, fontSize: 11, fontWeight: 700 }}>{project.progress}% filled</span></div>
    {project.status !== "COMPLETED" && <div style={{ height: 4, marginTop: 8, borderRadius: 99, overflow: "hidden", background: PANEL }}><div style={{ height: "100%", width: `${Math.max(project.progress, 2)}%`, background: `linear-gradient(90deg, ${GOLD}, ${GREEN})`, borderRadius: 99 }} /></div>}
  </motion.div>;
}

function SubscribeSheet({ project, onClose, onConfirm }: { project: Project; onClose: () => void; onConfirm: () => void }) {
  const [amount, setAmount] = useState("");
  const tokens = amount && project.tokenPriceUSD ? (+amount / project.tokenPriceUSD).toFixed(2) : "0.00";
  return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} style={{ position: "fixed", inset: 0, zIndex: 200, display: "flex", alignItems: "flex-end" }}><div onClick={onClose} style={{ position: "absolute", inset: 0, background: "rgba(0,0,0,.75)" }} /><motion.div initial={{ y: "100%" }} animate={{ y: 0 }} exit={{ y: "100%" }} transition={{ type: "spring", damping: 30, stiffness: 280 }} style={{ position: "relative", width: "100%", maxHeight: "90dvh", overflowY: "auto", borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: "8px 20px calc(34px + env(safe-area-inset-bottom))", background: "#1C1F26", borderTop: `1px solid ${LINE}` }}>
    <div style={{ width: 40, height: 4, borderRadius: 99, background: "rgba(255,255,255,.18)", margin: "0 auto 20px" }} /><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 18 }}><div style={{ display: "flex", alignItems: "center", gap: 10, minWidth: 0 }}><ProjectAvatar project={project} /><div style={{ minWidth: 0 }}><p style={{ color: FG, margin: 0, fontSize: 15, fontWeight: 700 }}>{project.name}</p><p style={{ color: DIM, margin: "3px 0 0", fontSize: 11 }}>{project.network} · {project.product}</p></div></div><button onClick={onClose} aria-label="Close" style={{ color: DIM, background: "none", border: 0, cursor: "pointer" }}><X size={20} /></button></div>
    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 1, background: LINE, borderRadius: 14, overflow: "hidden", marginBottom: 16 }}><div style={{ background: BG, padding: 13 }}><div style={{ color: DIM, fontSize: 11 }}>Token price</div><strong style={{ display: "block", color: FG, fontSize: 15, marginTop: 4 }}>{money(project.tokenPriceUSD)}</strong></div><div style={{ background: BG, padding: 13 }}><div style={{ color: DIM, fontSize: 11 }}>Max allocation</div><strong style={{ display: "block", color: FG, fontSize: 15, marginTop: 4 }}>{compact(project.maxAllocationToken)} {project.symbol}</strong></div></div>
    <div style={{ background: BG, border: `1px solid ${LINE}`, borderRadius: 16, padding: "12px 16px", marginBottom: 16 }}><div style={{ display: "flex", justifyContent: "space-between", color: DIM, fontSize: 11, marginBottom: 8 }}><span>Commitment (USDT)</span><span style={{ color: GOLD }}>≈ {tokens} {project.symbol}</span></div><input type="number" inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} placeholder="0.00" style={{ width: "100%", background: "transparent", border: 0, outline: 0, color: FG, fontSize: 24, fontWeight: 800, fontFamily: "inherit" }} /></div><button onClick={onConfirm} disabled={!amount || +amount <= 0} style={{ width: "100%", padding: 16, borderRadius: 16, border: 0, background: amount && +amount > 0 ? GOLD : PANEL, color: amount && +amount > 0 ? BG : DIM, fontWeight: 800, fontSize: 15, cursor: amount && +amount > 0 ? "pointer" : "not-allowed" }}>Check wallet & subscribe</button><p style={{ color: DIM, fontSize: 11, lineHeight: 1.55, margin: "14px 0 0" }}>Estimated allocation is not guaranteed. Review eligibility, project documents and risk disclosures before committing funds.</p>
  </motion.div></motion.div>;
}

export default function Launchpad() {
  const [, nav] = useLocation();
  const [tab, setTab] = useState("Launchpad");
  const [status, setStatus] = useState<FilterTab>("All");
  const [network, setNetwork] = useState("All networks");
  const [selected, setSelected] = useState<Project | null>(null);
  const [confirmed, setConfirmed] = useState(false);
  const list = useMemo(() => PROJECTS.filter(p => status === "All" || p.status === status.toUpperCase()).filter(p => network === "All networks" || p.network === network), [status, network]);
  const active = PROJECTS.find(p => p.status === "ACTIVE")!;
  const openProject = (p: Project) => setSelected(p);
  return <div style={{ minHeight: "100dvh", maxWidth: "100vw", overflowX: "hidden", background: BG, color: FG, fontFamily: "'Plus Jakarta Sans','Inter',sans-serif" }}>
    <div style={{ position: "sticky", top: 0, zIndex: 40, background: BG, borderBottom: `1px solid ${LINE}` }}>
      <div style={{ height: 52, display: "flex", alignItems: "center", padding: "0 12px 0 4px", overflowX: "auto", scrollbarWidth: "none" }}><button onClick={() => nav("/")} aria-label="Back" style={{ padding: "10px 12px", color: DIM, display: "flex", flexShrink: 0, background: "none", border: 0, cursor: "pointer" }}><ArrowLeft size={21} /></button>{TABS.map(t => <button key={t} onClick={() => setTab(t)} style={{ height: "100%", padding: "0 12px", flexShrink: 0, color: t === tab ? FG : DIM, fontSize: 14, fontWeight: t === tab ? 700 : 500, border: 0, borderBottom: `2.5px solid ${t === tab ? GREEN : "transparent"}`, background: "none", cursor: "pointer" }}>{t}</button>)}<div style={{ flex: 1 }} /><button style={{ display: "flex", alignItems: "center", gap: 5, padding: "7px 12px", borderRadius: 8, background: PANEL, color: FG, fontSize: 13, fontWeight: 600, border: `1px solid ${LINE}`, cursor: "pointer", flexShrink: 0 }}>OKZ <ChevronDown size={13} color={DIM} /></button></div>
      <div style={{ background: "#0F1115", padding: "7px 16px", overflow: "hidden" }}><p style={{ margin: 0, color: "#F6A609", fontSize: 11, whiteSpace: "nowrap", animation: "launchMarquee 34s linear infinite", display: "inline-block" }}>Stay vigilant against impersonators. Review project documents and eligibility before committing funds. No allocation is guaranteed.</p></div>
      <div style={{ display: "flex", alignItems: "center", padding: "10px 16px 8px" }}><div style={{ display: "flex", gap: 2, padding: 3, background: PANEL, borderRadius: 100 }}>{(["All", "Upcoming", "Active", "Completed"] as FilterTab[]).map(s => <button key={s} onClick={() => setStatus(s)} style={{ padding: "9px 15px", borderRadius: 100, background: status === s ? (s === "Active" ? GREEN : s === "Completed" ? RED : GOLD) : "transparent", color: status === s ? BG : DIM, border: 0, fontSize: 13, fontWeight: 700, cursor: "pointer", whiteSpace: "nowrap" }}>{s}</button>)}</div></div>
      <div style={{ display: "flex", alignItems: "center", gap: 8, padding: "0 16px 12px", overflowX: "auto", scrollbarWidth: "none" }}><button style={{ display: "flex", alignItems: "center", gap: 5, padding: "7px 12px", background: PANEL, borderRadius: 8, border: `1px solid ${LINE}`, color: FG, fontSize: 12, whiteSpace: "nowrap" }}>Token type <ChevronDown size={12} color={DIM} /></button><select value={network} onChange={e => setNetwork(e.target.value)} style={{ appearance: "none", padding: "7px 28px 7px 12px", background: PANEL, borderRadius: 8, border: `1px solid ${LINE}`, color: network === "All networks" ? DIM : FG, fontSize: 12, outline: 0, fontFamily: "inherit" }}><option>All networks</option><option>OKZ Chain</option><option>Ethereum</option><option>Arbitrum</option></select><button style={{ width: 36, height: 36, display: "grid", placeItems: "center", flexShrink: 0, background: PANEL, border: `1px solid ${LINE}`, borderRadius: 8, color: DIM }} aria-label="Filters"><Filter size={16} /></button></div>
    </div>
    <main style={{ maxWidth: 760, margin: "0 auto", padding: "10px 0 calc(84px + env(safe-area-inset-bottom))" }}>
      <section style={{ margin: "0 12px 14px", padding: 16, border: `1px solid ${GOLD}44`, borderRadius: 14, background: `linear-gradient(135deg, ${CARD}, #171B21)` }}><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12 }}><div style={{ display: "flex", alignItems: "center", gap: 10, minWidth: 0 }}><div style={{ width: 42, height: 42, display: "grid", placeItems: "center", flexShrink: 0, borderRadius: "50%", color: GOLD, background: `${GOLD}18`, border: `1px solid ${GOLD}55` }}><Zap size={19} /></div><div style={{ minWidth: 0 }}><div style={{ color: DIM, fontSize: 10, textTransform: "uppercase", letterSpacing: ".14em", fontWeight: 700 }}>Featured launch</div><div style={{ color: FG, fontSize: 18, fontWeight: 800, marginTop: 3 }}>{active.name}</div></div></div><StatusPill status={active.status} /></div><p style={{ color: DIM, fontSize: 12, lineHeight: 1.5, margin: "14px 0 13px" }}>{active.description}</p><div style={{ display: "flex", justifyContent: "space-between", gap: 12, alignItems: "flex-end" }}><div><span style={{ color: DIM, fontSize: 11 }}>Token price</span><strong style={{ display: "block", color: GREEN, fontSize: 22, marginTop: 3 }}>{money(active.tokenPriceUSD)}</strong></div><button onClick={() => openProject(active)} style={{ padding: "10px 18px", border: 0, borderRadius: 22, background: GOLD, color: BG, fontWeight: 800, cursor: "pointer" }}>Subscribe</button></div><div style={{ height: 4, marginTop: 14, background: PANEL, borderRadius: 99, overflow: "hidden" }}><div style={{ width: `${active.progress}%`, height: "100%", background: `linear-gradient(90deg, ${GOLD}, ${GREEN})` }} /></div></section>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 16px 10px" }}><div style={{ color: DIM, fontSize: 11, textTransform: "uppercase", letterSpacing: ".14em", fontWeight: 700 }}>Launch pipeline</div><span style={{ color: DIM, fontSize: 11 }}>{list.length} projects</span></div>
      <AnimatePresence mode="wait">{list.length ? <motion.div key={status + network} initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: .12 }}>{list.map(p => <ProjectCard key={p.id} project={p} onSelect={openProject} />)}</motion.div> : <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} style={{ textAlign: "center", color: DIM, padding: "70px 16px" }}><Rocket size={34} style={{ marginBottom: 10, opacity: .6 }} /><p style={{ margin: 0, fontWeight: 700 }}>No launches found</p><p style={{ margin: "5px 0 0", fontSize: 12 }}>Try another status or network filter.</p></motion.div>}</AnimatePresence>
      <section style={{ margin: "16px 12px 0", padding: 14, borderRadius: 12, border: `1px solid ${LINE}`, background: CARD, display: "flex", gap: 10 }}><ShieldCheck size={17} color={GREEN} style={{ flexShrink: 0 }} /><div><p style={{ color: FG, margin: 0, fontSize: 13, fontWeight: 700 }}>Participation checklist</p><p style={{ color: DIM, margin: "5px 0 0", fontSize: 11, lineHeight: 1.55 }}>Review eligibility, allocation rules, subscription dates and project documents before participating.</p><button onClick={() => nav("/feedback")} style={{ color: GOLD, marginTop: 8, padding: 0, background: "none", border: 0, fontSize: 11, fontWeight: 700, cursor: "pointer" }}>Contact support <ExternalLink size={11} style={{ verticalAlign: "-2px" }} /></button></div></section>
    </main>
    <div style={{ position: "fixed", left: 0, right: 0, bottom: 0, zIndex: 50, display: "flex", background: BG, borderTop: `1px solid ${LINE}`, paddingBottom: "env(safe-area-inset-bottom, 0px)" }}>{NAV.map(({ label, Icon, href }) => { const current = label === "Launchpad"; return <button key={label} onClick={() => nav(href)} style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 3, padding: "10px 0", color: current ? GOLD : DIM, background: "none", border: 0, cursor: "pointer" }}><Icon size={21} /><span style={{ fontSize: 10, fontWeight: current ? 700 : 500 }}>{label}</span>{current && <span style={{ width: 16, height: 2, borderRadius: 2, background: GOLD }} />}</button>; })}</div>
    <AnimatePresence>{selected && <SubscribeSheet project={selected} onClose={() => setSelected(null)} onConfirm={() => { setSelected(null); setConfirmed(true); }} />}</AnimatePresence>
    {confirmed && <div style={{ position: "fixed", inset: 0, zIndex: 220, display: "grid", placeItems: "center", padding: 16, background: "rgba(0,0,0,.78)" }}><div style={{ width: "100%", maxWidth: 360, padding: 22, textAlign: "center", background: "#151A21", border: `1px solid ${GOLD}55`, borderRadius: 18 }}><div style={{ width: 48, height: 48, display: "grid", placeItems: "center", margin: "0 auto", borderRadius: "50%", color: GREEN, background: `${GREEN}18` }}>✓</div><h3 style={{ color: FG, margin: "13px 0 0", fontSize: 17 }}>Wallet check required</h3><p style={{ color: DIM, margin: "7px 0 0", fontSize: 12, lineHeight: 1.55 }}>Connect and verify your wallet before subscribing to this launch.</p><button onClick={() => setConfirmed(false)} style={{ width: "100%", marginTop: 17, padding: 13, border: 0, borderRadius: 12, background: GOLD, color: BG, fontWeight: 800, cursor: "pointer" }}>Close</button></div></div>}
    <style>{`*{box-sizing:border-box;-webkit-tap-highlight-color:transparent}::-webkit-scrollbar{display:none}@keyframes launchMarquee{from{transform:translateX(100vw)}to{transform:translateX(-100%)}}@media(min-width:700px){main{padding-top:18px!important}.no-desktop{display:none}}select option{background:#1C1F26}`}</style>
  </div>;
}
