import { useMemo, useState } from "react";
import { useLocation } from "wouter";
import { ArrowLeft, BadgeCheck, Building2, ChevronRight, Clock3, Copy, Layers, Minus, Plus, ShieldCheck, TrendingUp, X } from "lucide-react";

const BG = "#040b14";
const PANEL = "#0b121d";
const CARD = "#101925";
const LINE = "rgba(255,255,255,.09)";
const TEXT = "#f2f4f7";
const DIM = "#8e99a8";
const GOLD = "#c9a84c";
const PINK = "#ec4899";
const GREEN = "#22c55e";

type AssetCategory = "All Fractional Assets" | "High Rental Yield" | "Commercial Outlets" | "Secondary Market Trading" | "Fully Funded Assets";
type FractionalAsset = { id: string; title: string; location: string; category: Exclude<AssetCategory, "All Fractional Assets">; sharePrice: number; totalValue: number; supply: number; sold: number; roi: string; dividendPerShare: number; status: string; accent: string; };

const ASSETS: FractionalAsset[] = [
  { id: "gulberg-galleria", title: "10th Floor Commercial Unit – Gulberg Galleria", location: "Gulberg III, Lahore", category: "Commercial Outlets", sharePrice: 5000, totalValue: 50000000, supply: 10000, sold: 6400, roi: "12.8% Expected ROI + Capital Appreciation", dividendPerShare: 120, status: "Monthly Rental Dividends", accent: "#06b6d4" },
  { id: "ocean-tower", title: "Ocean Tower Retail Frontage", location: "Karachi Waterfront", category: "High Rental Yield", sharePrice: 12500, totalValue: 125000000, supply: 10000, sold: 10000, roi: "15.4% Expected ROI", dividendPerShare: 230, status: "Fully Funded", accent: GOLD },
  { id: "orakzai-heights", title: "Orakzai Heights Residential RWA", location: "Islamabad Capital Territory", category: "High Rental Yield", sharePrice: 10000, totalValue: 80000000, supply: 8000, sold: 5320, roi: "11.6% Expected ROI", dividendPerShare: 155, status: "Monthly Rental Dividends", accent: GREEN },
  { id: "dha-secondary", title: "DHA Phase 9 Commercial Shares", location: "Lahore Smart District", category: "Secondary Market Trading", sharePrice: 7500, totalValue: 60000000, supply: 8000, sold: 4120, roi: "9.9% Expected ROI", dividendPerShare: 92, status: "Secondary Market Open", accent: PINK },
];

function money(value: number) { return `Rs ${Math.round(value).toLocaleString("en-PK")}`; }
function pct(sold: number, supply: number) { return Math.round((sold / supply) * 100); }

function PurchaseSheet({ asset, close, onPurchased }: { asset: FractionalAsset; close: () => void; onPurchased: (shares: number, amount: number) => void }) {
  const [tab, setTab] = useState<"buy" | "orderbook">("buy");
  const [shares, setShares] = useState(1);
  const [done, setDone] = useState(false);
  const total = shares * asset.sharePrice;
  const dividend = shares * asset.dividendPerShare;
  const orderBook = [{ side: "Buy", price: asset.sharePrice - 50, quantity: 42 }, { side: "Sell", price: asset.sharePrice + 75, quantity: 18 }, { side: "Buy", price: asset.sharePrice - 125, quantity: 76 }];
  const confirm = () => { onPurchased(shares, total); setDone(true); };
  return <div onClick={close} style={{ position: "fixed", inset: 0, zIndex: 80, background: "rgba(0,0,0,.7)", display: "flex", alignItems: "flex-end", justifyContent: "center" }}><div onClick={e => e.stopPropagation()} style={{ width: "100%", maxWidth: 520, maxHeight: "91dvh", overflowY: "auto", background: PANEL, border: `1px solid ${LINE}`, borderRadius: "22px 22px 0 0", padding: 18, color: TEXT, boxShadow: "0 -20px 60px rgba(0,0,0,.45)" }}>
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}><div><div style={{ color: PINK, fontSize: 10, fontWeight: 900, letterSpacing: ".14em" }}>FRACTIONAL OWNERSHIP</div><h2 style={{ margin: "7px 0 3px", fontSize: 18, lineHeight: 1.25 }}>{asset.title}</h2><div style={{ color: DIM, fontSize: 11 }}>{asset.location}</div></div><button aria-label="Close" onClick={close} style={{ border: 0, background: "transparent", color: DIM }}><X size={20} /></button></div>
    <div style={{ display: "flex", gap: 7, marginTop: 18 }}><button onClick={() => setTab("buy")} style={{ flex: 1, padding: 10, borderRadius: 10, border: `1px solid ${tab === "buy" ? `${PINK}99` : LINE}`, background: tab === "buy" ? `${PINK}16` : CARD, color: tab === "buy" ? PINK : DIM, fontWeight: 800, fontSize: 11 }}>Buy Shares</button><button onClick={() => setTab("orderbook")} style={{ flex: 1, padding: 10, borderRadius: 10, border: `1px solid ${tab === "orderbook" ? `${GOLD}99` : LINE}`, background: tab === "orderbook" ? `${GOLD}16` : CARD, color: tab === "orderbook" ? GOLD : DIM, fontWeight: 800, fontSize: 11 }}>Secondary Market</button></div>
    {tab === "buy" && !done && <><section style={{ marginTop: 14, padding: 14, borderRadius: 14, background: CARD, border: `1px solid ${LINE}` }}><div style={{ display: "flex", justifyContent: "space-between", color: DIM, fontSize: 10 }}><span>SHARES TO ACQUIRE</span><span>{money(asset.sharePrice)} / share</span></div><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginTop: 13 }}><button aria-label="Decrease shares" onClick={() => setShares(Math.max(1, shares - 1))} style={{ width: 38, height: 38, borderRadius: 10, border: `1px solid ${LINE}`, background: PANEL, color: TEXT }}><Minus size={16} /></button><div style={{ textAlign: "center" }}><strong style={{ display: "block", fontSize: 30 }}>{shares}</strong><span style={{ color: DIM, fontSize: 10 }}>SHARES</span></div><button aria-label="Increase shares" onClick={() => setShares(Math.min(asset.supply - asset.sold, shares + 1))} style={{ width: 38, height: 38, borderRadius: 10, border: `1px solid ${LINE}`, background: PANEL, color: TEXT }}><Plus size={16} /></button></div><input aria-label="Share quantity slider" type="range" min={1} max={Math.max(1, Math.min(250, asset.supply - asset.sold))} value={Math.min(shares, 250)} onChange={e => setShares(Number(e.target.value))} style={{ width: "100%", marginTop: 13, accentColor: PINK }} /></section><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginTop: 10 }}><div style={{ padding: 12, borderRadius: 11, background: CARD, border: `1px solid ${LINE}` }}><div style={{ color: DIM, fontSize: 10 }}>TOTAL COST</div><strong style={{ display: "block", marginTop: 5, fontSize: 17 }}>{money(total)}</strong></div><div style={{ padding: 12, borderRadius: 11, background: CARD, border: `1px solid ${LINE}` }}><div style={{ color: DIM, fontSize: 10 }}>EST. MONTHLY DIVIDEND</div><strong style={{ display: "block", marginTop: 5, color: GREEN, fontSize: 17 }}>{money(dividend)}</strong></div></div><div style={{ display: "flex", gap: 8, alignItems: "center", marginTop: 13, padding: 11, borderRadius: 10, background: `${PINK}0c`, border: `1px solid ${PINK}35`, color: DIM, fontSize: 10, lineHeight: 1.5 }}><ShieldCheck size={15} color={PINK} style={{ flexShrink: 0 }} />On-chain title, suitability checks, and documented ownership terms apply before settlement.</div><button onClick={confirm} style={{ width: "100%", marginTop: 15, padding: 13, border: 0, borderRadius: 12, background: PINK, color: "#fff", fontWeight: 900 }}>Buy Fractional Shares · {money(total)}</button></>}
    {tab === "orderbook" && <section style={{ marginTop: 14, borderRadius: 14, overflow: "hidden", background: CARD, border: `1px solid ${LINE}` }}><div style={{ padding: 13, borderBottom: `1px solid ${LINE}`, color: DIM, fontSize: 10 }}>LIVE ORDER BOOK · {asset.status}</div>{orderBook.map((row, i) => <div key={i} style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", padding: "12px 13px", borderBottom: i < orderBook.length - 1 ? `1px solid ${LINE}` : 0, fontSize: 11 }}><span style={{ color: row.side === "Buy" ? GREEN : "#f87171", fontWeight: 800 }}>{row.side}</span><span>{money(row.price)}</span><span style={{ textAlign: "right", color: DIM }}>{row.quantity} shares</span></div>)}</section>}
    {done && <div style={{ marginTop: 18, padding: 17, borderRadius: 14, border: `1px solid ${GREEN}40`, background: `${GREEN}0d`, textAlign: "center" }}><BadgeCheck size={28} color={GREEN} style={{ marginBottom: 8 }} /><h3 style={{ margin: 0, fontSize: 17 }}>Ownership recorded</h3><p style={{ color: DIM, fontSize: 11, lineHeight: 1.55 }}>Your fractional position has been added to the active ownership ledger.</p><button onClick={close} style={{ padding: "10px 18px", borderRadius: 10, border: 0, background: GOLD, color: BG, fontWeight: 900 }}>Done</button></div>}
  </div></div>;
}

export default function MarketFractional() {
  const [, navigate] = useLocation();
  const [category, setCategory] = useState<AssetCategory>("All Fractional Assets");
  const [selected, setSelected] = useState<FractionalAsset | null>(null);
  const [sharesOwned, setSharesOwned] = useState(() => Number(localStorage.getItem("okzbyte_fractional_shares") || 25));
  const [holdingsValue, setHoldingsValue] = useState(() => Number(localStorage.getItem("okzbyte_fractional_value") || 250000));
  const filtered = useMemo(() => category === "All Fractional Assets" ? ASSETS : ASSETS.filter(a => a.category === category || (category === "Fully Funded Assets" && a.sold === a.supply)), [category]);
  const monthly = Math.round(sharesOwned * 138);
  const onPurchased = (count: number, amount: number) => { const nextShares = sharesOwned + count; const nextValue = holdingsValue + amount; setSharesOwned(nextShares); setHoldingsValue(nextValue); localStorage.setItem("okzbyte_fractional_shares", String(nextShares)); localStorage.setItem("okzbyte_fractional_value", String(nextValue)); localStorage.setItem("okzbyte_fractional_last_receipt", JSON.stringify({ id: `FR-${Date.now().toString().slice(-8)}`, amount, shares: count, createdAt: new Date().toISOString() })); };
  return <main style={{ minHeight: "100dvh", background: BG, color: TEXT, fontFamily: "Inter, Plus Jakarta Sans, sans-serif", paddingBottom: 92 }}><div style={{ maxWidth: 560, margin: "0 auto", padding: "16px 16px 0" }}>
    <header style={{ display: "flex", alignItems: "center", gap: 12, paddingBottom: 18, borderBottom: `1px solid ${LINE}` }}><button aria-label="Back to Market" onClick={() => navigate("/market")} style={{ border: 0, background: "transparent", color: DIM, padding: 0 }}><ArrowLeft size={22} /></button><div><div style={{ color: PINK, fontSize: 10, fontWeight: 900, letterSpacing: ".14em" }}>FRACTIONAL MARKET</div><h1 style={{ margin: "4px 0 0", fontSize: 22 }}>Fractional Ownership</h1></div><div style={{ marginLeft: "auto", padding: "7px 9px", borderRadius: 10, background: `${PINK}14`, color: PINK, fontSize: 10, fontWeight: 900 }}>RWA SHARES</div></header>
    <section style={{ marginTop: 16, padding: 17, borderRadius: 17, background: `linear-gradient(135deg, ${PINK}20, ${CARD} 52%)`, border: `1px solid ${PINK}38` }}><div style={{ display: "flex", alignItems: "center", gap: 9 }}><div style={{ width: 35, height: 35, display: "grid", placeItems: "center", borderRadius: 11, background: `${PINK}22` }}><Layers size={18} color={PINK} /></div><div><div style={{ color: DIM, fontSize: 10, fontWeight: 800, letterSpacing: ".1em" }}>MY FRACTIONAL HOLDINGS</div><div style={{ color: DIM, fontSize: 11, marginTop: 3 }}>Diversified micro-ownership portfolio</div></div></div><div style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", gap: 12, marginTop: 18 }}><div><strong style={{ display: "block", fontSize: 28 }}>{money(holdingsValue)}</strong><span style={{ color: DIM, fontSize: 11 }}>{sharesOwned} Shares Across 3 Properties</span></div><div style={{ padding: "9px 10px", borderRadius: 10, background: `${GREEN}12`, border: `1px solid ${GREEN}30`, textAlign: "right" }}><div style={{ color: DIM, fontSize: 9 }}>MONTHLY RENTAL YIELD</div><strong style={{ display: "block", marginTop: 4, color: GREEN, fontSize: 16 }}>{money(monthly)} / mo</strong></div></div></section>
    <div style={{ display: "flex", gap: 7, overflowX: "auto", padding: "15px 0 7px", scrollbarWidth: "none" }}>{(["All Fractional Assets", "High Rental Yield", "Commercial Outlets", "Secondary Market Trading", "Fully Funded Assets"] as AssetCategory[]).map(item => <button key={item} onClick={() => setCategory(item)} style={{ whiteSpace: "nowrap", padding: "9px 11px", borderRadius: 10, border: `1px solid ${category === item ? `${PINK}88` : LINE}`, background: category === item ? `${PINK}18` : PANEL, color: category === item ? PINK : DIM, fontSize: 10, fontWeight: 800 }}>{item}</button>)}</div>
    <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", margin: "15px 0 10px" }}><div><div style={{ color: PINK, fontSize: 10, fontWeight: 900, letterSpacing: ".12em" }}>TOKENIZED ASSETS</div><h2 style={{ margin: "5px 0 0", fontSize: 17 }}>Fractional opportunities</h2></div><div style={{ color: DIM, fontSize: 10 }}>{filtered.length} assets</div></div>
    <div style={{ display: "grid", gap: 11 }}>{filtered.map(asset => { const funded = pct(asset.sold, asset.supply); return <article key={asset.id} onClick={() => setSelected(asset)} style={{ padding: 14, borderRadius: 15, background: CARD, border: `1px solid ${LINE}`, cursor: "pointer", transition: "transform .18s ease" }}><div style={{ display: "flex", alignItems: "flex-start", gap: 10 }}><div style={{ width: 38, height: 38, display: "grid", placeItems: "center", flexShrink: 0, borderRadius: 12, background: `${asset.accent}18` }}><Building2 size={19} color={asset.accent} /></div><div style={{ minWidth: 0, flex: 1 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 8 }}><h3 style={{ margin: 0, fontSize: 14, lineHeight: 1.3 }}>{asset.title}</h3><ChevronRight size={17} color={DIM} style={{ flexShrink: 0 }} /></div><div style={{ marginTop: 4, color: DIM, fontSize: 10 }}>{asset.location}</div></div></div><div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginTop: 12 }}><span style={{ padding: "5px 7px", borderRadius: 7, background: `${GREEN}12`, color: GREEN, fontSize: 9, fontWeight: 900 }}>{asset.roi}</span><span style={{ padding: "5px 7px", borderRadius: 7, background: `${PINK}12`, color: PINK, fontSize: 9, fontWeight: 900 }}>On-Chain Verified</span><span style={{ padding: "5px 7px", borderRadius: 7, background: PANEL, color: DIM, fontSize: 9, fontWeight: 800 }}>{asset.status}</span></div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginTop: 11 }}><div style={{ padding: 10, borderRadius: 10, background: PANEL }}><div style={{ color: DIM, fontSize: 9 }}>PRICE / SHARE</div><strong style={{ display: "block", marginTop: 4, fontSize: 14 }}>{money(asset.sharePrice)}</strong></div><div style={{ padding: 10, borderRadius: 10, background: PANEL }}><div style={{ color: DIM, fontSize: 9 }}>TOTAL ASSET VALUE</div><strong style={{ display: "block", marginTop: 4, fontSize: 14 }}>{money(asset.totalValue)}</strong></div></div><div style={{ marginTop: 11 }}><div style={{ display: "flex", justifyContent: "space-between", color: DIM, fontSize: 9 }}><span>{asset.sold.toLocaleString()} / {asset.supply.toLocaleString()} Shares Sold</span><strong style={{ color: asset.sold === asset.supply ? GREEN : TEXT }}>{funded}%</strong></div><div style={{ height: 6, marginTop: 6, borderRadius: 99, background: "rgba(255,255,255,.08)", overflow: "hidden" }}><div style={{ width: `${funded}%`, height: "100%", borderRadius: 99, background: asset.sold === asset.supply ? GREEN : `linear-gradient(90deg, ${PINK}, ${GOLD})` }} /></div></div><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8, marginTop: 12, color: DIM, fontSize: 10 }}><span><TrendingUp size={13} color={GREEN} style={{ verticalAlign: "-2px", marginRight: 4 }} />{money(asset.dividendPerShare)} est. monthly / share</span><span style={{ color: GOLD, fontWeight: 900 }}>Review asset</span></div></article>; })}</div>
    <div style={{ display: "flex", gap: 8, alignItems: "center", marginTop: 16, padding: 12, borderRadius: 12, background: PANEL, border: `1px solid ${LINE}`, color: DIM, fontSize: 10, lineHeight: 1.5 }}><ShieldCheck size={15} color={GOLD} style={{ flexShrink: 0 }} />Fractional property ownership is subject to KYC, offering documents, title verification, and applicable transfer restrictions.</div>
  </div>{selected && <PurchaseSheet asset={selected} close={() => setSelected(null)} onPurchased={onPurchased} />}</main>;
}
