import { useMemo, useState } from "react";
import { ArrowLeft, BadgeCheck, Building2, ChevronRight, ClipboardList, HardHat, MapPin, MessageCircle, Minus, Plus, Search, ShieldCheck, Truck, X } from "lucide-react";
import { useLocation } from "wouter";

const BG = "#040b14";
const PANEL = "#0b121d";
const CARD = "#101925";
const LINE = "rgba(255,255,255,.09)";
const TEXT = "#f2f4f7";
const DIM = "#8e99a8";
const GOLD = "#c9a84c";
const ORANGE = "#f97316";
const GREEN = "#22c55e";

type Category = "All Materials" | "Cement & Concrete" | "Steel & Rebar" | "Bricks & Blocks" | "Finishing & Tiles" | "Sanitary & Electrical";
type Product = { id: string; name: string; brand: string; category: Exclude<Category, "All Materials">; price: number; unit: string; moq: number; stock: number; delivery: string; supplier: string; supplierType: string; accent: string; };

const PRODUCTS: Product[] = [
  { id: "cement-maple", name: "Grade A Portland Cement – 50kg Bag", brand: "Maple Leaf", category: "Cement & Concrete", price: 1350, unit: "Bag", moq: 50, stock: 5000, delivery: "Express Site Delivery", supplier: "Maple Leaf Authorized Distributor", supplierType: "Authorized Distributor", accent: "#f59e0b" },
  { id: "steel-mughal", name: "Grade 60 Deformed Steel Bars", brand: "Mughal Steel", category: "Steel & Rebar", price: 285000, unit: "Ton", moq: 1, stock: 120, delivery: "Scheduled Fleet Delivery", supplier: "Mughal Steel Official Channel", supplierType: "Verified Manufacturer", accent: "#60a5fa" },
  { id: "brick-premium", name: "A-Class Red Clay Bricks", brand: "Punjab Brickworks", category: "Bricks & Blocks", price: 18500, unit: "1,000 Pieces", moq: 5, stock: 85, delivery: "Local Site Delivery", supplier: "Punjab Brickworks", supplierType: "Verified Manufacturer", accent: "#ef4444" },
  { id: "tiles-master", name: "Porcelain Floor Tiles 60×60", brand: "Master Tiles", category: "Finishing & Tiles", price: 295, unit: "Sq. Ft.", moq: 200, stock: 18000, delivery: "Express Site Delivery", supplier: "Master Tiles Authorized Partner", supplierType: "Authorized Distributor", accent: "#a78bfa" },
  { id: "sanitary-sonex", name: "Premium Bathroom Sanitary Suite", brand: "Sonex", category: "Sanitary & Electrical", price: 68500, unit: "Set", moq: 1, stock: 240, delivery: "White-Glove Delivery", supplier: "Sonex Official Showroom", supplierType: "Verified Manufacturer", accent: "#06b6d4" },
  { id: "cable-pak", name: "6mm Copper Electrical Cable", brand: "Pakistan Cables", category: "Sanitary & Electrical", price: 42500, unit: "Roll", moq: 5, stock: 640, delivery: "Nationwide Dispatch", supplier: "Pakistan Cables Distributor", supplierType: "Authorized Distributor", accent: GREEN },
];

const categories: Category[] = ["All Materials", "Cement & Concrete", "Steel & Rebar", "Bricks & Blocks", "Finishing & Tiles", "Sanitary & Electrical"];
function money(value: number) { return `Rs ${Math.round(value).toLocaleString("en-PK")}`; }

function QuoteModal({ product, close }: { product?: Product; close: () => void }) {
  const [quantity, setQuantity] = useState(product?.moq || 50);
  const [address, setAddress] = useState("Lahore – DHA Phase 6");
  const [mode, setMode] = useState<"order" | "quote">("order");
  const [done, setDone] = useState(false);
  const [quoteSent, setQuoteSent] = useState(false);
  const unitPrice = product?.price || 1350;
  const discount = quantity >= (product?.moq || 50) * 20 ? 0.08 : quantity >= (product?.moq || 50) * 5 ? 0.04 : 0;
  const freight = address.includes("Islamabad") ? 18000 : address.includes("Karachi") ? 35000 : 8500;
  const subtotal = unitPrice * quantity;
  const total = Math.round(subtotal * (1 - discount) + freight);
  const sendQuote = () => setQuoteSent(true);
  const placeOrder = () => setDone(true);
  return <div onClick={close} style={{ position: "fixed", inset: 0, zIndex: 80, background: "rgba(0,0,0,.72)", display: "flex", alignItems: "flex-end", justifyContent: "center" }}><div onClick={e => e.stopPropagation()} style={{ width: "100%", maxWidth: 520, maxHeight: "91dvh", overflowY: "auto", background: PANEL, border: `1px solid ${LINE}`, borderRadius: "22px 22px 0 0", padding: 18, color: TEXT }}>
    <div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}><div><div style={{ color: ORANGE, fontSize: 10, fontWeight: 900, letterSpacing: ".14em" }}>{mode === "quote" ? "WHOLESALE RFP" : "BULK ORDER DESK"}</div><h2 style={{ margin: "7px 0 3px", fontSize: 18, lineHeight: 1.3 }}>{product?.name || "Bulk construction materials request"}</h2>{product && <div style={{ color: DIM, fontSize: 11 }}>{product.brand} · {product.supplier}</div>}</div><button aria-label="Close" onClick={close} style={{ border: 0, background: "transparent", color: DIM }}><X size={20} /></button></div>
    <div style={{ display: "flex", gap: 7, marginTop: 16 }}><button onClick={() => setMode("order")} style={{ flex: 1, padding: 10, borderRadius: 10, border: `1px solid ${mode === "order" ? `${ORANGE}99` : LINE}`, background: mode === "order" ? `${ORANGE}18` : CARD, color: mode === "order" ? ORANGE : DIM, fontWeight: 800, fontSize: 11 }}>Direct Order</button><button onClick={() => setMode("quote")} style={{ flex: 1, padding: 10, borderRadius: 10, border: `1px solid ${mode === "quote" ? `${GOLD}99` : LINE}`, background: mode === "quote" ? `${GOLD}18` : CARD, color: mode === "quote" ? GOLD : DIM, fontWeight: 800, fontSize: 11 }}>Request Quote</button></div>
    {mode === "order" && !done && <><section style={{ marginTop: 14, padding: 14, borderRadius: 14, background: CARD, border: `1px solid ${LINE}` }}><div style={{ display: "flex", justifyContent: "space-between", color: DIM, fontSize: 10 }}><span>ORDER QUANTITY</span><span>{product ? `${money(unitPrice)} / ${product.unit}` : "Specify units"}</span></div><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginTop: 13 }}><button aria-label="Decrease quantity" onClick={() => setQuantity(Math.max(product?.moq || 1, quantity - (product?.moq || 1)))} style={{ width: 38, height: 38, borderRadius: 10, border: `1px solid ${LINE}`, background: PANEL, color: TEXT }}><Minus size={16} /></button><div style={{ textAlign: "center" }}><strong style={{ display: "block", fontSize: 27 }}>{quantity.toLocaleString()}</strong><span style={{ color: DIM, fontSize: 10 }}>{product?.unit || "UNITS"}</span></div><button aria-label="Increase quantity" onClick={() => setQuantity(quantity + (product?.moq || 1))} style={{ width: 38, height: 38, borderRadius: 10, border: `1px solid ${LINE}`, background: PANEL, color: TEXT }}><Plus size={16} /></button></div></section><label style={{ display: "block", marginTop: 13, color: DIM, fontSize: 10, fontWeight: 800 }}>DELIVERY DESTINATION<select value={address} onChange={e => setAddress(e.target.value)} style={{ display: "block", width: "100%", marginTop: 7, padding: 12, borderRadius: 10, border: `1px solid ${LINE}`, background: CARD, color: TEXT }}><option>Lahore – DHA Phase 6</option><option>Islamabad – Gulberg Greens</option><option>Karachi – DHA Phase 8</option><option>Punjab Wide – Site Delivery</option></select></label><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginTop: 11 }}><div style={{ padding: 12, borderRadius: 11, background: CARD, border: `1px solid ${LINE}` }}><div style={{ color: DIM, fontSize: 9 }}>DISCOUNT</div><strong style={{ display: "block", color: GREEN, marginTop: 4, fontSize: 15 }}>{discount ? `${discount * 100}% Tier Discount` : "Standard Rate"}</strong></div><div style={{ padding: 12, borderRadius: 11, background: CARD, border: `1px solid ${LINE}` }}><div style={{ color: DIM, fontSize: 9 }}>EST. FREIGHT</div><strong style={{ display: "block", marginTop: 4, fontSize: 15 }}>{money(freight)}</strong></div></div><div style={{ display: "flex", justifyContent: "space-between", marginTop: 14, paddingTop: 13, borderTop: `1px solid ${LINE}` }}><span style={{ color: DIM, fontSize: 11 }}>Estimated total</span><strong style={{ fontSize: 21 }}>{money(total)}</strong></div><button onClick={placeOrder} style={{ width: "100%", marginTop: 14, padding: 13, border: 0, borderRadius: 12, background: ORANGE, color: "#fff", fontWeight: 900 }}>Place Direct Order · {money(total)}</button></>}
    {mode === "quote" && !quoteSent && <><label style={{ display: "block", marginTop: 14, color: DIM, fontSize: 10, fontWeight: 800 }}>REQUIRED QUANTITY / PROJECT SCOPE<textarea placeholder="e.g. 500 bags for a 10-marla residential project" style={{ display: "block", width: "100%", minHeight: 96, marginTop: 7, padding: 12, borderRadius: 10, border: `1px solid ${LINE}`, background: CARD, color: TEXT, resize: "vertical" }} /></label><label style={{ display: "block", marginTop: 12, color: DIM, fontSize: 10, fontWeight: 800 }}>SITE DELIVERY LOCATION<input placeholder="Project address, city, or area" style={{ display: "block", width: "100%", marginTop: 7, padding: 12, borderRadius: 10, border: `1px solid ${LINE}`, background: CARD, color: TEXT }} /></label><button onClick={sendQuote} style={{ width: "100%", marginTop: 14, padding: 13, border: 0, borderRadius: 12, background: GOLD, color: BG, fontWeight: 900 }}>Request Wholesale Quote</button></>}
    {(done || quoteSent) && <div style={{ marginTop: 17, padding: 17, borderRadius: 14, background: `${GREEN}0d`, border: `1px solid ${GREEN}40`, textAlign: "center" }}><BadgeCheck size={28} color={GREEN} /><h3 style={{ margin: "8px 0 4px", fontSize: 17 }}>{done ? "Order request recorded" : "Wholesale inquiry sent"}</h3><p style={{ margin: 0, color: DIM, fontSize: 11, lineHeight: 1.5 }}>{done ? "The supplier will confirm stock, payment route, and delivery timing." : "The supplier desk will respond with a negotiated quote and logistics plan."}</p><button onClick={close} style={{ marginTop: 13, padding: "10px 18px", borderRadius: 10, border: 0, background: GOLD, color: BG, fontWeight: 900 }}>Done</button></div>}
  </div></div>;
}

export default function MarketConstruction() {
  const [, navigate] = useLocation();
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState<Category>("All Materials");
  const [selected, setSelected] = useState<Product | undefined>();
  const [bulkOpen, setBulkOpen] = useState(false);
  const products = useMemo(() => PRODUCTS.filter(p => (category === "All Materials" || p.category === category) && `${p.name} ${p.brand} ${p.supplier} ${p.category}`.toLowerCase().includes(query.toLowerCase())), [category, query]);
  return <main style={{ minHeight: "100dvh", background: BG, color: TEXT, fontFamily: "Inter, Plus Jakarta Sans, sans-serif", paddingBottom: 92 }}><div style={{ maxWidth: 560, margin: "0 auto", padding: "16px 16px 0" }}>
    <header style={{ display: "flex", alignItems: "center", gap: 12, paddingBottom: 16, borderBottom: `1px solid ${LINE}` }}><button aria-label="Back to Market" onClick={() => navigate("/market")} style={{ border: 0, background: "transparent", color: DIM, padding: 0 }}><ArrowLeft size={22} /></button><div><div style={{ color: ORANGE, fontSize: 10, fontWeight: 900, letterSpacing: ".14em" }}>CONSTRUCTION MARKET</div><h1 style={{ margin: "4px 0 0", fontSize: 22 }}>Construction & Materials</h1></div></header>
    <div style={{ position: "relative", marginTop: 16 }}><Search size={17} color={DIM} style={{ position: "absolute", left: 13, top: 13 }} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search steel, cement, tiles, suppliers..." style={{ width: "100%", boxSizing: "border-box", padding: "12px 13px 12px 38px", borderRadius: 12, border: `1px solid ${LINE}`, background: PANEL, color: TEXT }} /></div>
    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginTop: 10 }}><button onClick={() => setBulkOpen(true)} style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 7, padding: 11, borderRadius: 11, border: `1px solid ${ORANGE}55`, background: `${ORANGE}12`, color: ORANGE, fontWeight: 900, fontSize: 11 }}><ClipboardList size={15} />Bulk Order Quote</button><button onClick={() => navigate("/market/services-directory")} style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 7, padding: 11, borderRadius: 11, border: `1px solid ${GOLD}55`, background: `${GOLD}12`, color: GOLD, fontWeight: 900, fontSize: 11 }}><HardHat size={15} />Hire Contractor</button></div>
    <div style={{ display: "flex", gap: 7, overflowX: "auto", padding: "15px 0 6px", scrollbarWidth: "none" }}>{categories.map(item => <button key={item} onClick={() => setCategory(item)} style={{ whiteSpace: "nowrap", padding: "9px 11px", borderRadius: 10, border: `1px solid ${category === item ? `${ORANGE}88` : LINE}`, background: category === item ? `${ORANGE}18` : PANEL, color: category === item ? ORANGE : DIM, fontSize: 10, fontWeight: 800 }}>{item}</button>)}</div>
    <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", margin: "14px 0 10px" }}><div><div style={{ color: ORANGE, fontSize: 10, fontWeight: 900, letterSpacing: ".12em" }}>VERIFIED SUPPLY NETWORK</div><h2 style={{ margin: "5px 0 0", fontSize: 17 }}>Materials & suppliers</h2></div><span style={{ color: DIM, fontSize: 10 }}>{products.length} products</span></div>
    <div style={{ display: "grid", gap: 11 }}>{products.map(product => <article key={product.id} onClick={() => setSelected(product)} style={{ padding: 14, borderRadius: 15, background: CARD, border: `1px solid ${LINE}`, cursor: "pointer" }}><div style={{ display: "flex", alignItems: "flex-start", gap: 10 }}><div style={{ width: 38, height: 38, display: "grid", placeItems: "center", flexShrink: 0, borderRadius: 12, background: `${product.accent}18` }}><Building2 size={19} color={product.accent} /></div><div style={{ flex: 1, minWidth: 0 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 8 }}><h3 style={{ margin: 0, fontSize: 14, lineHeight: 1.3 }}>{product.name}</h3><ChevronRight size={17} color={DIM} style={{ flexShrink: 0 }} /></div><div style={{ marginTop: 4, color: DIM, fontSize: 10 }}>{product.brand} · {product.category}</div></div></div><div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginTop: 12 }}><span style={{ padding: "5px 7px", borderRadius: 7, background: `${ORANGE}14`, color: ORANGE, fontSize: 9, fontWeight: 900 }}>{money(product.price)} / {product.unit}</span><span style={{ padding: "5px 7px", borderRadius: 7, background: PANEL, color: DIM, fontSize: 9, fontWeight: 800 }}>MOQ: {product.moq.toLocaleString()} {product.unit}</span><span style={{ padding: "5px 7px", borderRadius: 7, background: `${GREEN}12`, color: GREEN, fontSize: 9, fontWeight: 900 }}>In Stock · {product.stock.toLocaleString()}</span></div><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8, marginTop: 12, paddingTop: 10, borderTop: `1px solid ${LINE}`, color: DIM, fontSize: 10 }}><span><Truck size={13} color={GREEN} style={{ verticalAlign: "-2px", marginRight: 4 }} />{product.delivery}</span><span style={{ color: GOLD, fontWeight: 900 }}><ShieldCheck size={13} style={{ verticalAlign: "-2px", marginRight: 3 }} />{product.supplierType}</span></div></article>)}</div>
    {products.length === 0 && <div style={{ padding: 28, marginTop: 12, borderRadius: 14, background: CARD, border: `1px solid ${LINE}`, textAlign: "center", color: DIM, fontSize: 12 }}>No materials match your search. Try another product, brand, or category.</div>}
    <div style={{ display: "flex", gap: 8, alignItems: "center", marginTop: 16, padding: 12, borderRadius: 12, background: PANEL, border: `1px solid ${LINE}`, color: DIM, fontSize: 10, lineHeight: 1.5 }}><ShieldCheck size={15} color={ORANGE} style={{ flexShrink: 0 }} />Supplier verification, product availability, freight, and final pricing are confirmed before settlement.</div>
  </div>{(selected || bulkOpen) && <QuoteModal product={selected} close={() => { setSelected(undefined); setBulkOpen(false); }} />}</main>;
}
