import React, { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Banknote, ChevronRight, Clock3, Globe2, History, LockKeyhole, Search, ShieldCheck, Smartphone, WalletCards, X } from "lucide-react";
import { useLocation } from "wouter";
import { useToast } from "@/hooks/use-toast";

const C = { bg: "#0b0e11", card: "#181a20", panel: "#0b0e11", line: "#2b313a", text: "#f5f5f5", muted: "#929aa5", green: "#0ecb81" };
const assets = ["USDT", "BTC", "OKBOND", "ETH"];
type Region = { code: string; name: string; flag: string; currency: string; symbol: string; rate: number; methods: { name: string; icon: React.ElementType; best?: boolean; time: string }[] };
const REGIONS: Region[] = [
  { code: "PK", name: "Pakistan", flag: "🇵🇰", currency: "PKR", symbol: "Rs", rate: 282.5, methods: [{ name: "Bank Transfer / Raast", icon: Banknote, best: true, time: "Instant · 0% fee" }, { name: "EasyPaisa", icon: Smartphone, time: "1–3 min" }, { name: "JazzCash", icon: WalletCards, time: "1–3 min" }] },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪", currency: "AED", symbol: "AED", rate: 3.673, methods: [{ name: "UAE Bank Transfer · Mashreq / ENBD / FAB", icon: Banknote, best: true, time: "5–15 min" }, { name: "Cash Deposit at ATM", icon: WalletCards, time: "15–30 min" }, { name: "ADCB Hayyak", icon: Smartphone, time: "1–3 min" }] },
  { code: "US", name: "United States", flag: "🇺🇸", currency: "USD", symbol: "$", rate: 1, methods: [{ name: "Zelle Instant", icon: Smartphone, best: true, time: "Instant" }, { name: "Wire / ACH Bank Transfer", icon: Banknote, time: "1–3 business days" }, { name: "Wise", icon: WalletCards, time: "5–20 min" }] },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧", currency: "GBP", symbol: "£", rate: 0.79, methods: [{ name: "Faster Payments (FPS)", icon: Banknote, best: true, time: "Instant" }, { name: "Revolut", icon: Smartphone, time: "1–3 min" }, { name: "Wise", icon: WalletCards, time: "5–20 min" }] },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦", currency: "SAR", symbol: "SAR", rate: 3.75, methods: [{ name: "STC Pay", icon: Smartphone, best: true, time: "Instant" }, { name: "Urpay", icon: WalletCards, time: "1–3 min" }, { name: "Local Saudi Bank · Al Rajhi / SNB", icon: Banknote, time: "5–15 min" }] },
  { code: "QA", name: "Qatar", flag: "🇶🇦", currency: "QAR", symbol: "QAR", rate: 3.64, methods: [{ name: "Qatar Bank Transfer", icon: Banknote, best: true, time: "5–15 min" }, { name: "Ooredoo Money", icon: Smartphone, time: "1–3 min" }, { name: "Wise", icon: WalletCards, time: "5–20 min" }] },
  { code: "IN", name: "India", flag: "🇮🇳", currency: "INR", symbol: "₹", rate: 83.4, methods: [{ name: "UPI Instant", icon: Smartphone, best: true, time: "Instant" }, { name: "IMPS / NEFT Bank Transfer", icon: Banknote, time: "5–15 min" }, { name: "Wise", icon: WalletCards, time: "5–20 min" }] },
  { code: "EU", name: "Eurozone", flag: "🇪🇺", currency: "EUR", symbol: "€", rate: 0.92, methods: [{ name: "SEPA Instant", icon: Banknote, best: true, time: "Instant" }, { name: "Revolut", icon: Smartphone, time: "1–3 min" }, { name: "Wise", icon: WalletCards, time: "5–20 min" }] },
];
const wrapper = { minHeight: "100dvh", background: C.bg, color: C.text, padding: "12px 16px calc(100px + env(safe-area-inset-bottom))", fontFamily: "-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif", overflowX: "hidden" } as const;

function formatRate(value: number) { return value < 10 ? value.toFixed(3) : value.toLocaleString("en-US", { maximumFractionDigits: 2 }); }

export default function P2PExpress() {
  const [, nav] = useLocation();
  const { toast } = useToast();
  const [side, setSide] = useState<"BUY" | "SELL">("BUY");
  const [asset, setAsset] = useState("USDT");
  const [basis, setBasis] = useState<"fiat" | "crypto">("fiat");
  const [amount, setAmount] = useState("25000");
  const [method, setMethod] = useState(0);
  const [open, setOpen] = useState(false);
  const [history, setHistory] = useState(false);
  const [regionOpen, setRegionOpen] = useState(false);
  const [regionSearch, setRegionSearch] = useState("");
  const [region, setRegion] = useState<Region>(REGIONS[0]);

  useEffect(() => {
    const saved = typeof window !== "undefined" ? window.localStorage.getItem("user_p2p_country") : null;
    const found = REGIONS.find(item => item.code === saved);
    if (found) setRegion(found);
  }, []);

  const selectRegion = (next: Region) => {
    setRegion(next);
    setMethod(0);
    setRegionOpen(false);
    setRegionSearch("");
    window.localStorage.setItem("user_p2p_country", next.code);
    toast({ title: `${next.flag} ${next.name} selected`, description: `P2P payment methods and ${next.currency} rates updated.` });
  };

  const rate = asset === "BTC" ? region.rate * 66900 : asset === "ETH" ? region.rate * 2765 : region.rate;
  const receive = useMemo(() => basis === "fiat" ? Number(amount || 0) / rate : Number(amount || 0) * rate, [amount, rate, basis]);
  const formatted = receive ? receive.toLocaleString("en-US", { maximumFractionDigits: 6 }) : "0.00";
  const submit = () => {
    const minimum = region.currency === "PKR" ? 1000 : 10;
    if (!Number(amount) || Number(amount) < minimum) { toast({ title: "Amount below minimum", description: `Enter at least ${region.symbol} ${minimum.toLocaleString()} ${region.currency}.` }); return; }
    setOpen(true);
  };
  const filteredRegions = REGIONS.filter(item => `${item.name} ${item.currency}`.toLowerCase().includes(regionSearch.toLowerCase()));

  return <div style={wrapper}>
    <header style={{ height: 48, display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 12 }}><div style={{ display: "flex", alignItems: "center", gap: 8 }}><button onClick={() => nav("/services")} style={{ padding: 8, border: 0, background: "none", color: C.muted }}><ArrowLeft size={20} /></button><strong style={{ fontSize: 16, letterSpacing: .2 }}>P2P Express</strong></div><div style={{ display: "flex", gap: 5, alignItems: "center" }}><button onClick={() => setHistory(true)} style={{ padding: 8, border: 0, background: "none", color: C.muted }}><History size={18} /></button><span style={{ padding: "6px 9px", borderRadius: 8, border: `1px solid ${C.line}`, background: C.card, color: C.text, fontSize: 10, fontWeight: 900 }}>{region.flag} {region.currency}</span></div></header>
    <main style={{ maxWidth: 620, margin: "0 auto" }}>
      <button onClick={() => setRegionOpen(true)} style={{ width: "100%", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10, marginBottom: 14, padding: 12, borderRadius: 16, border: `1px solid ${C.line}`, background: C.card, color: C.text, textAlign: "left", cursor: "pointer" }}><span style={{ display: "flex", alignItems: "center", gap: 10 }}><span style={{ display: "grid", placeItems: "center", width: 34, height: 34, borderRadius: 10, background: `${C.green}15`, color: C.green }}><Globe2 size={18} /></span><span><strong style={{ display: "block", fontSize: 12 }}>{region.flag} {region.name}</strong><small style={{ display: "block", marginTop: 3, color: C.muted, fontSize: 9 }}>Local P2P settlement region</small></span></span><span style={{ display: "flex", alignItems: "center", gap: 8 }}><b style={{ padding: "5px 8px", borderRadius: 6, background: `${C.green}18`, color: C.green, fontSize: 10 }}>{region.currency}</b><span style={{ color: C.green, fontSize: 10, fontWeight: 800, whiteSpace: "nowrap" }}>Change Region →</span></span></button>
      <div style={{ display: "flex", gap: 4, padding: 4, marginBottom: 14, borderRadius: 12, border: `1px solid ${C.line}`, background: C.card }}>{(["BUY", "SELL"] as const).map(x => <button key={x} onClick={() => setSide(x)} style={{ width: "50%", padding: "10px 0", border: 0, borderRadius: 9, background: side === x ? C.green : "transparent", color: side === x ? "#07100b" : C.muted, fontSize: 11, fontWeight: 900 }}>{x}</button>)}</div>
      <div style={{ display: "flex", gap: 8, overflowX: "auto", marginBottom: 14 }}>{assets.map(x => <button key={x} onClick={() => setAsset(x)} style={{ whiteSpace: "nowrap", padding: "7px 13px", borderRadius: 999, border: `1px solid ${asset === x ? C.green + "66" : C.line}`, background: asset === x ? "#2b313a" : C.card, color: asset === x ? C.green : C.muted, fontSize: 10, fontWeight: 900 }}>{x}</button>)}</div>
      <section style={{ padding: 16, borderRadius: 17, border: `1px solid ${C.line}`, background: C.card, boxShadow: "0 10px 30px rgba(0,0,0,.24)" }}><div style={{ display: "flex", gap: 16, marginBottom: 13 }}><button onClick={() => setBasis("fiat")} style={{ padding: 0, border: 0, borderBottom: basis === "fiat" ? `2px solid ${C.green}` : "2px solid transparent", background: "none", color: basis === "fiat" ? C.green : C.muted, fontSize: 11, fontWeight: 800 }}>By Fiat ({region.currency})</button><button onClick={() => setBasis("crypto")} style={{ padding: 0, border: 0, borderBottom: basis === "crypto" ? `2px solid ${C.green}` : "2px solid transparent", background: "none", color: basis === "crypto" ? C.green : C.muted, fontSize: 11, fontWeight: 800 }}>By Crypto ({asset})</button></div><div style={{ padding: 14, borderRadius: 12, border: `1px solid ${C.line}`, background: C.panel, marginBottom: 12 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 8 }}><span style={{ color: C.muted, fontSize: 11, fontWeight: 700 }}>{side === "BUY" ? "Amount to Spend" : "Amount to Receive"}</span><span style={{ color: C.muted, fontSize: 9 }}>Min {region.symbol} {region.currency === "PKR" ? "1,000" : "10"}</span></div><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, marginTop: 8 }}><input inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value.replace(/[^0-9.]/g, ""))} placeholder={`${region.symbol} 0.00`} style={{ width: "70%", border: 0, outline: 0, background: "transparent", color: C.text, fontSize: 22, fontWeight: 900, fontFamily: "monospace" }} /><strong style={{ color: C.green, fontSize: 11 }}>{basis === "fiat" ? region.currency : asset}</strong></div></div><div style={{ display: "grid", gap: 8, padding: 12, borderRadius: 12, border: `1px solid ${C.line}`, background: "rgba(11,14,17,.6)", fontSize: 11 }}><div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}><span style={{ color: C.muted }}>Reference Price</span><strong style={{ color: C.green, fontFamily: "monospace" }}>1 {asset} ≈ {region.symbol} {formatRate(rate)} {region.currency}</strong></div><div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}><span style={{ color: C.muted }}>You Receive Approx.</span><strong style={{ color: C.text, fontFamily: "monospace", fontSize: 14 }}>{basis === "fiat" ? `${formatted} ${asset}` : `${formatted} ${region.currency}`}</strong></div><div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}><span style={{ color: C.muted }}>Transaction Fee</span><strong style={{ color: C.green }}>0.00 {region.currency} (Zero Fee)</strong></div></div></section>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", margin: "19px 4px 9px" }}><span style={{ color: C.muted, fontSize: 10, fontWeight: 900, letterSpacing: 1, textTransform: "uppercase" }}>Pay via {region.name}</span><span style={{ color: C.green, fontSize: 10, fontWeight: 800 }}>Local gateways</span></div>
      <div style={{ display: "grid", gap: 8 }}>{region.methods.map((m, i) => { const Icon = m.icon; return <button key={m.name} onClick={() => setMethod(i)} style={{ display: "flex", alignItems: "center", justifyContent: "space-between", width: "100%", padding: 13, borderRadius: 12, border: `1px solid ${method === i ? C.green + "88" : C.line}`, background: C.panel, color: C.text, textAlign: "left" }}><span style={{ display: "flex", alignItems: "center", gap: 10 }}><span style={{ width: 32, height: 32, display: "grid", placeItems: "center", borderRadius: 9, background: method === i ? `${C.green}18` : `${C.line}55`, color: method === i ? C.green : C.muted }}><Icon size={16} /></span><span><strong style={{ display: "block", fontSize: 11 }}>{m.name}</strong><small style={{ display: "block", marginTop: 3, color: C.muted, fontSize: 9 }}><Clock3 size={10} style={{ verticalAlign: "-2px", marginRight: 3 }} />{m.time} settlement</small></span></span>{m.best && <span style={{ padding: "4px 7px", borderRadius: 5, background: `${C.green}20`, color: C.green, fontSize: 9, fontWeight: 900 }}>Best Price</span>}</button>; })}</div>
      <button onClick={submit} style={{ width: "100%", marginTop: 18, padding: "14px 0", border: 0, borderRadius: 12, background: C.green, color: "#06110b", fontSize: 12, fontWeight: 900 }}>{side === "BUY" ? `Buy ${asset} with 0 Fee` : `Sell ${asset} with 0 Fee`}</button><div style={{ display: "flex", justifyContent: "center", alignItems: "center", gap: 5, marginTop: 10, color: C.muted, fontSize: 10 }}><LockKeyhole size={12} color={C.green} /> Protected by OkzByte Institutional Escrow Lock</div><div style={{ display: "flex", justifyContent: "center", gap: 5, alignItems: "center", marginTop: 14, color: C.muted, fontSize: 9 }}><ShieldCheck size={12} color={C.green} /> Verified merchants only · Funds held in escrow until settlement</div>
    </main>
    {regionOpen && <div style={{ position: "fixed", inset: 0, zIndex: 110, display: "flex", alignItems: "flex-end", background: "rgba(0,0,0,.72)", backdropFilter: "blur(6px)" }} onClick={() => setRegionOpen(false)}><section onClick={e => e.stopPropagation()} style={{ width: "100%", maxHeight: "84vh", overflowY: "auto", padding: "22px 16px calc(32px + env(safe-area-inset-bottom))", borderRadius: "24px 24px 0 0", background: C.card, borderTop: `1px solid ${C.green}55` }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 15 }}><div><strong style={{ fontSize: 16 }}>Choose your region</strong><p style={{ margin: "5px 0 0", color: C.muted, fontSize: 10 }}>Payment methods and fiat rates update automatically.</p></div><button onClick={() => setRegionOpen(false)} style={{ border: 0, background: "none", color: C.muted }}><X size={19} /></button></div><div style={{ display: "flex", alignItems: "center", gap: 8, padding: "10px 12px", borderRadius: 11, border: `1px solid ${C.line}`, background: C.panel, marginBottom: 14 }}><Search size={15} color={C.muted} /><input autoFocus value={regionSearch} onChange={e => setRegionSearch(e.target.value)} placeholder="Search country or currency" style={{ flex: 1, border: 0, outline: 0, background: "transparent", color: C.text, fontSize: 12 }} /></div><div style={{ display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: 8 }}>{filteredRegions.map(item => <button key={item.code} onClick={() => selectRegion(item)} style={{ display: "flex", alignItems: "center", gap: 9, padding: 11, borderRadius: 12, border: `1px solid ${region.code === item.code ? C.green + "88" : C.line}`, background: region.code === item.code ? `${C.green}12` : C.panel, color: C.text, textAlign: "left" }}><span style={{ fontSize: 21 }}>{item.flag}</span><span style={{ minWidth: 0 }}><strong style={{ display: "block", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontSize: 11 }}>{item.name}</strong><small style={{ display: "block", marginTop: 3, color: C.green, fontSize: 9, fontWeight: 800 }}>{item.currency}</small></span></button>)}</div></section></div>}
    {open && <div style={{ position: "fixed", inset: 0, zIndex: 100, display: "flex", alignItems: "flex-end", background: "rgba(0,0,0,.72)", backdropFilter: "blur(6px)" }} onClick={() => setOpen(false)}><section onClick={e => e.stopPropagation()} style={{ width: "100%", maxHeight: "88vh", overflowY: "auto", padding: "22px 16px calc(30px + env(safe-area-inset-bottom))", borderRadius: "24px 24px 0 0", background: C.card, borderTop: `1px solid ${C.green}55` }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 18 }}><div><strong style={{ fontSize: 16 }}>Review {side === "BUY" ? "Buy" : "Sell"} Order</strong><p style={{ margin: "5px 0 0", color: C.muted, fontSize: 11 }}>Matched with the best {region.name} merchant</p></div><button onClick={() => setOpen(false)} style={{ padding: 7, border: 0, background: "none", color: C.muted }}><X size={18} /></button></div><div style={{ display: "grid", gap: 10, padding: 14, borderRadius: 14, background: C.panel, border: `1px solid ${C.line}`, fontSize: 11 }}><div style={{ display: "flex", justifyContent: "space-between" }}><span style={{ color: C.muted }}>Region</span><strong>{region.flag} {region.name}</strong></div><div style={{ display: "flex", justifyContent: "space-between" }}><span style={{ color: C.muted }}>Asset</span><strong>{asset}</strong></div><div style={{ display: "flex", justifyContent: "space-between" }}><span style={{ color: C.muted }}>Amount</span><strong>{basis === "fiat" ? `${Number(amount || 0).toLocaleString()} ${region.currency}` : `${amount} ${asset}`}</strong></div><div style={{ display: "flex", justifyContent: "space-between" }}><span style={{ color: C.muted }}>Payment</span><strong>{region.methods[method]?.name}</strong></div><div style={{ display: "flex", justifyContent: "space-between" }}><span style={{ color: C.muted }}>Fee</span><strong style={{ color: C.green }}>0.00 {region.currency}</strong></div></div><button onClick={() => { setOpen(false); toast({ title: "P2P order created", description: `${region.flag} ${region.currency} order protected by institutional escrow.` }); }} style={{ width: "100%", marginTop: 16, padding: 14, border: 0, borderRadius: 12, background: C.green, color: "#06110b", fontSize: 12, fontWeight: 900 }}>Confirm & Continue</button></section></div>}
    {history && <div style={{ position: "fixed", inset: 0, zIndex: 100, display: "flex", alignItems: "flex-end", background: "rgba(0,0,0,.72)", backdropFilter: "blur(6px)" }} onClick={() => setHistory(false)}><section onClick={e => e.stopPropagation()} style={{ width: "100%", padding: "20px 16px calc(28px + env(safe-area-inset-bottom))", borderRadius: "24px 24px 0 0", background: C.card }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><strong>Express Orders</strong><button onClick={() => setHistory(false)} style={{ border: 0, background: "none", color: C.muted }}><X size={18} /></button></div><div style={{ display: "flex", gap: 10, marginTop: 16, padding: 12, borderRadius: 12, background: C.panel, border: `1px solid ${C.line}` }}><History size={16} color={C.green} /><div><strong style={{ display: "block", fontSize: 11 }}>USDT Buy · 25,000 {region.currency}</strong><span style={{ display: "block", marginTop: 4, color: C.green, fontSize: 10 }}>Completed · {region.symbol} settlement</span></div></div></section></div>}
    <nav style={{ position: "fixed", inset: "auto 0 0", zIndex: 50, height: "calc(52px + env(safe-area-inset-bottom))", paddingBottom: "env(safe-area-inset-bottom)", display: "flex", justifyContent: "space-around", alignItems: "center", background: "rgba(11,14,17,.97)", borderTop: `1px solid ${C.line}`, backdropFilter: "blur(16px)" }}>{[["Home", "/"], ["Markets", "/markets"], ["Trade", "/trade"], ["Services", "/services"], ["Wallet", "/wallet"]].map(([label, href]) => <button key={label} onClick={() => nav(href)} style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 3, border: 0, background: "none", color: label === "Trade" ? C.green : C.muted, fontSize: 10, fontWeight: 700 }}>{label}</button>)}</nav>
  </div>;
}
