import { useMemo, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useLocation } from "wouter";
import {
  ArrowLeft, Search, History, Headphones, FilePenLine, ShieldCheck, WalletCards,
  Building2, CandlestickChart, ChevronRight, ChevronDown, X, MessageCircle,
  Paperclip, Send, Clock3, CircleHelp, ExternalLink, CheckCircle2,
} from "lucide-react";

const BG = "#0b0e11", CARD = "#181a20", PANEL = "#1e2329", LINE = "#2b313a", GOLD = "#f0b90b", GREEN = "#0ecb81", DIM = "#929aa5", FG = "#f5f5f5";

type Topic = { id: string; title: string; subtitle: string; icon: typeof ShieldCheck; answers: string[] };
const TOPICS: Topic[] = [
  { id: "security", title: "Security & KYC", subtitle: "2FA, Passkeys, ID verification guidelines", icon: ShieldCheck, answers: ["Open Security Center to manage 2FA, passkeys and withdrawal protection.", "KYC reviews are processed after identity documents are submitted and verified."] },
  { id: "payouts", title: "Deposits & Payouts", subtitle: "PKR Local Transfers, TRC20, BEP20 processing", icon: WalletCards, answers: ["Confirm the destination network before sending crypto.", "Local PKR processing depends on bank and compliance checks."] },
  { id: "rwa", title: "RWA & Staking Vaults", subtitle: "DHAISB & ASC fractional property rules", icon: Building2, answers: ["RWA products show APY, lock term, custody status and minimum stake before confirmation.", "Review redemption and risk disclosures before allocating funds."] },
  { id: "trading", title: "Trading & Fees", subtitle: "Limit/Market orders, fee tiers, trading limits", icon: CandlestickChart, answers: ["Market orders execute against available order-book liquidity.", "Fee tiers and order limits are shown in the trading interface before submission."] },
];
const QUESTIONS = ["How long does local PKR withdrawal take?", "What is the minimum amount for RWA staking?", "Why is my 2FA authentication code failing?"];

function Sheet({ kind, topic, onClose }: { kind: "tickets" | "chat" | "ticket" | "topic"; topic?: Topic; onClose: () => void }) {
  const [message, setMessage] = useState("");
  const [sent, setSent] = useState(false);
  return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} style={{ position: "fixed", inset: 0, zIndex: 1000, display: "flex", alignItems: "flex-end", background: "rgba(0,0,0,.78)" }}>
    <div onClick={onClose} style={{ position: "absolute", inset: 0 }} />
    <motion.div initial={{ y: "100%" }} animate={{ y: 0 }} exit={{ y: "100%" }} style={{ position: "relative", width: "100%", maxHeight: "90dvh", overflowY: "auto", padding: "22px 16px calc(32px + env(safe-area-inset-bottom) + 64px)", background: BG, borderTop: `1px solid ${LINE}`, borderRadius: "24px 24px 0 0" }}>
      <div style={{ width: 40, height: 4, borderRadius: 99, background: LINE, margin: "0 auto 18px" }} />
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><strong style={{ fontSize: 16 }}>{kind === "tickets" ? "My Tickets" : kind === "chat" ? "Live Chat Support" : kind === "ticket" ? "Submit Support Ticket" : topic?.title}</strong><button onClick={onClose} style={{ border: 0, background: "none", color: DIM }}><X size={20} /></button></div>
      {kind === "tickets" && <div style={{ marginTop: 18, padding: 18, borderRadius: 14, background: CARD, border: `1px solid ${LINE}`, textAlign: "center" }}><History size={26} color={GOLD} style={{ marginBottom: 8 }} /><strong style={{ display: "block" }}>No active tickets</strong><span style={{ display: "block", color: DIM, fontSize: 11, marginTop: 6 }}>Your support requests will appear here with status and response history.</span></div>}
      {kind === "chat" && <div style={{ marginTop: 18 }}><div style={{ padding: 14, borderRadius: 14, background: `${GREEN}10`, border: `1px solid ${GREEN}35`, color: DIM, fontSize: 12, lineHeight: 1.6 }}>A support specialist is available. Average response time is under 2 minutes during live coverage.</div><button onClick={() => setSent(true)} style={{ width: "100%", marginTop: 16, padding: 14, border: 0, borderRadius: 12, background: GREEN, color: BG, fontWeight: 900 }}>{sent ? "Chat request sent" : "Connect to live chat"}</button></div>}
      {kind === "ticket" && <div style={{ marginTop: 18 }}><label style={{ display: "block", color: DIM, fontSize: 11, marginBottom: 7 }}>Describe your issue</label><textarea value={message} onChange={e => setMessage(e.target.value.slice(0, 1000))} placeholder="Include the relevant transaction ID or account context..." style={{ width: "100%", minHeight: 130, resize: "vertical", boxSizing: "border-box", padding: 13, borderRadius: 12, border: `1px solid ${LINE}`, background: PANEL, color: FG, outline: "none", fontFamily: "inherit" }} /><div style={{ display: "flex", justifyContent: "space-between", color: DIM, fontSize: 10, marginTop: 6 }}><span><Paperclip size={12} style={{ verticalAlign: "-2px" }} /> Optional attachments</span><span>{message.length}/1000</span></div><button disabled={!message.trim()} onClick={() => setSent(true)} style={{ width: "100%", marginTop: 16, padding: 14, border: 0, borderRadius: 12, background: message.trim() ? GOLD : `${GOLD}44`, color: BG, fontWeight: 900 }}>{sent ? "Ticket submitted" : "Submit ticket"}</button></div>}
      {kind === "topic" && topic && <div style={{ marginTop: 18 }}>{topic.answers.map((answer, i) => <div key={i} style={{ padding: 14, marginBottom: 9, borderRadius: 13, background: CARD, border: `1px solid ${LINE}`, color: DIM, fontSize: 12, lineHeight: 1.65 }}><CheckCircle2 size={15} color={GREEN} style={{ verticalAlign: "-3px", marginRight: 7 }} />{answer}</div>)}</div>}
      <button onClick={onClose} style={{ width: "100%", marginTop: 16, marginBottom: 8, padding: 13, border: `1px solid ${LINE}`, borderRadius: 12, background: CARD, color: FG, fontWeight: 800 }}>Close</button>
    </motion.div>
  </motion.div>;
}

export default function Support() {
  const [, setLocation] = useLocation();
  const [search, setSearch] = useState("");
  const [sheet, setSheet] = useState<"tickets" | "chat" | "ticket" | "topic" | null>(null);
  const [topic, setTopic] = useState<Topic | undefined>();
  const [openQuestion, setOpenQuestion] = useState<number | null>(null);
  const filteredTopics = useMemo(() => TOPICS.filter(t => `${t.title} ${t.subtitle}`.toLowerCase().includes(search.toLowerCase())), [search]);
  const openTopic = (t: Topic) => { setTopic(t); setSheet("topic"); };
  return <div style={{ minHeight: "100dvh", background: BG, color: FG, padding: "12px 16px calc(88px + env(safe-area-inset-bottom))", fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", boxSizing: "border-box" }}>
    <header style={{ height: 48, display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 12 }}><div style={{ display: "flex", alignItems: "center", gap: 10 }}><button onClick={() => setLocation("/services")} style={{ border: 0, background: "none", color: FG, padding: 3 }}><ArrowLeft size={21} /></button><strong style={{ fontSize: 16, letterSpacing: ".02em" }}>Help & Support</strong></div><div style={{ display: "flex", alignItems: "center", gap: 8 }}><button onClick={() => setSheet("tickets")} style={{ border: `1px solid ${GOLD}33`, borderRadius: 999, padding: "7px 11px", background: PANEL, color: GOLD, fontSize: 11, fontWeight: 800 }}>My Tickets</button><button onClick={() => setSheet("tickets")} style={{ border: 0, background: "none", color: DIM }}><History size={19} /></button></div></header>
    <section style={{ padding: 20, marginBottom: 18, borderRadius: 18, border: `1px solid ${LINE}`, background: `linear-gradient(110deg, ${CARD}, ${PANEL}, ${BG})`, boxShadow: "0 14px 36px rgba(0,0,0,.22)" }}><h1 style={{ margin: "0 0 14px", fontSize: 19 }}>How can we help you today?</h1><div style={{ position: "relative" }}><Search size={16} color={DIM} style={{ position: "absolute", left: 12, top: 13 }} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search help articles, topics or keywords" style={{ width: "100%", boxSizing: "border-box", padding: "12px 14px 12px 38px", borderRadius: 12, border: `1px solid ${LINE}`, background: BG, color: FG, outline: "none", fontSize: 12 }} /></div><div style={{ display: "flex", gap: 8, overflowX: "auto", paddingTop: 10 }}><span style={{ color: DIM, fontSize: 10, alignSelf: "center", whiteSpace: "nowrap" }}>Quick assist</span>{["Reset 2FA", "Pending Deposit", "KYC Verification", "RWA Payouts"].map(p => <button key={p} onClick={() => setSearch(p)} style={{ whiteSpace: "nowrap", padding: "7px 10px", borderRadius: 8, border: `1px solid ${LINE}`, background: CARD, color: DIM, fontSize: 10 }}>{p}</button>)}</div></section>
    <div style={{ display: "grid", gridTemplateColumns: "repeat(2, minmax(0,1fr))", gap: 10, marginBottom: 24 }}><ActionCard icon={<Headphones size={20} />} color={GREEN} title="Live Chat Support" subtitle="Average response < 2 mins" action="Start Chat" onClick={() => setSheet("chat")} /><ActionCard icon={<FilePenLine size={20} />} color={GOLD} title="Submit Request" subtitle="Complex technical issues" action="New Ticket" onClick={() => setSheet("ticket")} /></div>
    <SectionTitle>POPULAR HELP TOPICS</SectionTitle><div>{filteredTopics.map(t => <button key={t.id} onClick={() => openTopic(t)} style={{ width: "100%", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, padding: 14, marginBottom: 9, textAlign: "left", borderRadius: 15, border: `1px solid ${LINE}`, background: CARD, color: FG }}><div style={{ display: "flex", alignItems: "center", gap: 12, minWidth: 0 }}><div style={{ width: 38, height: 38, display: "grid", placeItems: "center", flexShrink: 0, borderRadius: 11, background: `${GOLD}14`, color: GOLD }}><t.icon size={19} /></div><div style={{ minWidth: 0 }}><strong style={{ display: "block", fontSize: 13 }}>{t.title}</strong><span style={{ display: "block", marginTop: 4, color: DIM, fontSize: 10 }}>{t.subtitle}</span></div></div><ChevronRight size={17} color={DIM} /></button>)}</div>
    <SectionTitle>TOP QUESTIONS</SectionTitle><div>{QUESTIONS.map((q, i) => <div key={q} style={{ borderBottom: `1px solid ${LINE}` }}><button onClick={() => setOpenQuestion(openQuestion === i ? null : i)} style={{ width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", padding: "13px 2px", border: 0, background: "none", color: FG, textAlign: "left", fontSize: 12, fontWeight: 700 }}><span>{q}</span>{openQuestion === i ? <ChevronDown size={16} color={GOLD} /> : <ChevronRight size={16} color={DIM} />}</button>{openQuestion === i && <div style={{ padding: "0 22px 13px 2px", color: DIM, fontSize: 11, lineHeight: 1.6 }}>{i === 0 ? "Local withdrawals are processed after bank and compliance checks; timing can vary by transfer rail." : i === 1 ? "The minimum is shown on each RWA vault card and may vary by product, lock term and eligibility." : "Check device time sync, authenticator backup codes and the selected account before requesting support."}</div>}</div>)}</div>
    <div style={{ display: "flex", gap: 10, alignItems: "center", marginTop: 22, padding: 13, borderRadius: 13, background: `${GOLD}0c`, border: `1px solid ${GOLD}28`, color: DIM, fontSize: 10 }}><CircleHelp size={17} color={GOLD} /><span>Never share a password, recovery phrase or private key with support.</span><ExternalLink size={14} color={GOLD} /></div>
    <AnimatePresence>{sheet && <Sheet kind={sheet} topic={topic} onClose={() => setSheet(null)} />}</AnimatePresence>
  </div>;
}
function SectionTitle({ children }: { children: string }) { return <div style={{ color: DIM, fontSize: 10, fontWeight: 800, letterSpacing: ".13em", margin: "0 0 10px 2px" }}>{children}</div>; }
function ActionCard({ icon, color, title, subtitle, action, onClick }: { icon: React.ReactNode; color: string; title: string; subtitle: string; action: string; onClick: () => void }) { return <div style={{ minWidth: 0, padding: 14, borderRadius: 16, border: `1px solid ${color}44`, background: CARD }}><div style={{ color, display: "flex", justifyContent: "space-between" }}>{icon}<span style={{ width: 7, height: 7, marginTop: 4, borderRadius: "50%", background: color }} /></div><strong style={{ display: "block", marginTop: 12, fontSize: 12 }}>{title}</strong><span style={{ display: "block", marginTop: 4, minHeight: 26, color: DIM, fontSize: 10 }}>{subtitle}</span><button onClick={onClick} style={{ width: "100%", marginTop: 12, padding: "9px 5px", borderRadius: 9, border: `1px solid ${color}55`, background: `${color}12`, color, fontSize: 10, fontWeight: 800 }}>{action}</button></div>; }
