// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/OkzbyteLaunchpad.tsx": () => import("../components/mockups/OkzbyteLaunchpad.tsx"),
  "./components/mockups/withdraw-flow/WithdrawFlow.tsx": () => import("../components/mockups/withdraw-flow/WithdrawFlow.tsx")
};
